################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/AlphaFunc.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/AnimationPath.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/AutoTransform.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/Billboard.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/BlendColor.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/BlendEquation.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/BlendFunc.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/Box.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/Camera.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/CameraView.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/Capsule.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/ClearNode.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/ClipNode.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/ClipPlane.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/ClusterCullingCallback.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/ColorMask.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/ColorMatrix.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/CompositeShape.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/Cone.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/ConvexPlanarOccluder.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/CoordinateSystemNode.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/CullFace.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/Cylinder.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/Depth.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/Drawable.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/EllipsoidModel.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/Fog.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/FragmentProgram.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/FrontFace.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/Geode.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/Geometry.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/Group.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/HeightField.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/Image.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/ImageSequence.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/LOD.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/LibraryWrapper.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/Light.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/LightModel.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/LightSource.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/LineStipple.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/LineWidth.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/Material.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/Matrix.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/MatrixTransform.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/Node.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/NodeCallback.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/Object.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/OccluderNode.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/OcclusionQueryNode.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/PagedLOD.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/Point.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/PointSprite.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/PolygonMode.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/PolygonOffset.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/PositionAttitudeTransform.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/Program.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/Projection.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/ProxyNode.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/Scissor.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/Sequence.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/ShadeModel.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/Shader.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/ShapeDrawable.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/Sphere.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/StateAttribute.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/StateSet.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/Stencil.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/Switch.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/TessellationHints.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/TexEnv.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/TexEnvCombine.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/TexEnvFilter.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/TexGen.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/TexGenNode.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/TexMat.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/Texture.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/Texture1D.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/Texture2D.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/Texture3D.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/TextureCubeMap.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/TextureRectangle.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/TransferFunction.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/Transform.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/Uniform.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/VertexProgram.cpp \
../src/osg/src/osgWrappers/deprecated-dotosg/osg/Viewport.cpp 

OBJS += \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/AlphaFunc.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/AnimationPath.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/AutoTransform.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Billboard.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/BlendColor.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/BlendEquation.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/BlendFunc.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Box.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Camera.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/CameraView.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Capsule.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/ClearNode.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/ClipNode.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/ClipPlane.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/ClusterCullingCallback.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/ColorMask.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/ColorMatrix.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/CompositeShape.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Cone.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/ConvexPlanarOccluder.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/CoordinateSystemNode.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/CullFace.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Cylinder.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Depth.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Drawable.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/EllipsoidModel.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Fog.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/FragmentProgram.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/FrontFace.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Geode.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Geometry.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Group.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/HeightField.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Image.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/ImageSequence.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/LOD.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/LibraryWrapper.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Light.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/LightModel.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/LightSource.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/LineStipple.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/LineWidth.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Material.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Matrix.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/MatrixTransform.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Node.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/NodeCallback.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Object.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/OccluderNode.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/OcclusionQueryNode.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/PagedLOD.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Point.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/PointSprite.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/PolygonMode.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/PolygonOffset.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/PositionAttitudeTransform.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Program.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Projection.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/ProxyNode.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Scissor.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Sequence.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/ShadeModel.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Shader.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/ShapeDrawable.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Sphere.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/StateAttribute.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/StateSet.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Stencil.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Switch.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/TessellationHints.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/TexEnv.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/TexEnvCombine.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/TexEnvFilter.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/TexGen.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/TexGenNode.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/TexMat.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Texture.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Texture1D.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Texture2D.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Texture3D.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/TextureCubeMap.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/TextureRectangle.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/TransferFunction.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Transform.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Uniform.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/VertexProgram.o \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Viewport.o 

CPP_DEPS += \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/AlphaFunc.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/AnimationPath.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/AutoTransform.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Billboard.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/BlendColor.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/BlendEquation.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/BlendFunc.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Box.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Camera.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/CameraView.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Capsule.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/ClearNode.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/ClipNode.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/ClipPlane.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/ClusterCullingCallback.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/ColorMask.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/ColorMatrix.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/CompositeShape.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Cone.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/ConvexPlanarOccluder.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/CoordinateSystemNode.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/CullFace.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Cylinder.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Depth.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Drawable.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/EllipsoidModel.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Fog.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/FragmentProgram.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/FrontFace.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Geode.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Geometry.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Group.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/HeightField.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Image.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/ImageSequence.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/LOD.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/LibraryWrapper.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Light.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/LightModel.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/LightSource.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/LineStipple.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/LineWidth.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Material.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Matrix.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/MatrixTransform.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Node.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/NodeCallback.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Object.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/OccluderNode.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/OcclusionQueryNode.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/PagedLOD.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Point.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/PointSprite.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/PolygonMode.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/PolygonOffset.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/PositionAttitudeTransform.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Program.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Projection.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/ProxyNode.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Scissor.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Sequence.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/ShadeModel.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Shader.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/ShapeDrawable.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Sphere.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/StateAttribute.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/StateSet.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Stencil.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Switch.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/TessellationHints.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/TexEnv.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/TexEnvCombine.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/TexEnvFilter.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/TexGen.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/TexGenNode.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/TexMat.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Texture.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Texture1D.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Texture2D.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Texture3D.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/TextureCubeMap.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/TextureRectangle.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/TransferFunction.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Transform.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Uniform.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/VertexProgram.d \
./src/osg/src/osgWrappers/deprecated-dotosg/osg/Viewport.d 


# Each subdirectory must supply rules for building sources it contributes
src/osg/src/osgWrappers/deprecated-dotosg/osg/%.o: ../src/osg/src/osgWrappers/deprecated-dotosg/osg/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: Cross G++ Compiler'
	g++ -std=c++11 -I/usr/include/gtk-3.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/pixman-1 -I/usr/include/libpng12 -O0 -g3 -Wall -c -fmessage-length=0 `pkg-config --cflags gtk+-3.0` -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


