################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../src/osg/src/osgWrappers/serializers/osg/AlphaFunc.cpp \
../src/osg/src/osgWrappers/serializers/osg/AnimationPath.cpp \
../src/osg/src/osgWrappers/serializers/osg/AnimationPathCallback.cpp \
../src/osg/src/osgWrappers/serializers/osg/Array.cpp \
../src/osg/src/osgWrappers/serializers/osg/AudioSink.cpp \
../src/osg/src/osgWrappers/serializers/osg/AudioStream.cpp \
../src/osg/src/osgWrappers/serializers/osg/AutoTransform.cpp \
../src/osg/src/osgWrappers/serializers/osg/Billboard.cpp \
../src/osg/src/osgWrappers/serializers/osg/BlendColor.cpp \
../src/osg/src/osgWrappers/serializers/osg/BlendEquation.cpp \
../src/osg/src/osgWrappers/serializers/osg/BlendEquationi.cpp \
../src/osg/src/osgWrappers/serializers/osg/BlendFunc.cpp \
../src/osg/src/osgWrappers/serializers/osg/BlendFunci.cpp \
../src/osg/src/osgWrappers/serializers/osg/Box.cpp \
../src/osg/src/osgWrappers/serializers/osg/Callback.cpp \
../src/osg/src/osgWrappers/serializers/osg/Camera.cpp \
../src/osg/src/osgWrappers/serializers/osg/CameraView.cpp \
../src/osg/src/osgWrappers/serializers/osg/Capsule.cpp \
../src/osg/src/osgWrappers/serializers/osg/ClampColor.cpp \
../src/osg/src/osgWrappers/serializers/osg/ClearNode.cpp \
../src/osg/src/osgWrappers/serializers/osg/ClipNode.cpp \
../src/osg/src/osgWrappers/serializers/osg/ClipPlane.cpp \
../src/osg/src/osgWrappers/serializers/osg/ClusterCullingCallback.cpp \
../src/osg/src/osgWrappers/serializers/osg/ColorMask.cpp \
../src/osg/src/osgWrappers/serializers/osg/ColorMaski.cpp \
../src/osg/src/osgWrappers/serializers/osg/ColorMatrix.cpp \
../src/osg/src/osgWrappers/serializers/osg/CompositeShape.cpp \
../src/osg/src/osgWrappers/serializers/osg/ComputeBoundingBoxCallback.cpp \
../src/osg/src/osgWrappers/serializers/osg/Cone.cpp \
../src/osg/src/osgWrappers/serializers/osg/ConvexHull.cpp \
../src/osg/src/osgWrappers/serializers/osg/ConvexPlanarOccluder.cpp \
../src/osg/src/osgWrappers/serializers/osg/CoordinateSystemNode.cpp \
../src/osg/src/osgWrappers/serializers/osg/CullFace.cpp \
../src/osg/src/osgWrappers/serializers/osg/Cylinder.cpp \
../src/osg/src/osgWrappers/serializers/osg/Depth.cpp \
../src/osg/src/osgWrappers/serializers/osg/DrawPixels.cpp \
../src/osg/src/osgWrappers/serializers/osg/Drawable.cpp \
../src/osg/src/osgWrappers/serializers/osg/EllipsoidModel.cpp \
../src/osg/src/osgWrappers/serializers/osg/Fog.cpp \
../src/osg/src/osgWrappers/serializers/osg/FragmentProgram.cpp \
../src/osg/src/osgWrappers/serializers/osg/FrontFace.cpp \
../src/osg/src/osgWrappers/serializers/osg/Geode.cpp \
../src/osg/src/osgWrappers/serializers/osg/Geometry.cpp \
../src/osg/src/osgWrappers/serializers/osg/Group.cpp \
../src/osg/src/osgWrappers/serializers/osg/HeightField.cpp \
../src/osg/src/osgWrappers/serializers/osg/Hint.cpp \
../src/osg/src/osgWrappers/serializers/osg/Image.cpp \
../src/osg/src/osgWrappers/serializers/osg/ImageSequence.cpp \
../src/osg/src/osgWrappers/serializers/osg/ImageStream.cpp \
../src/osg/src/osgWrappers/serializers/osg/LOD.cpp \
../src/osg/src/osgWrappers/serializers/osg/LibraryWrapper.cpp \
../src/osg/src/osgWrappers/serializers/osg/Light.cpp \
../src/osg/src/osgWrappers/serializers/osg/LightModel.cpp \
../src/osg/src/osgWrappers/serializers/osg/LightSource.cpp \
../src/osg/src/osgWrappers/serializers/osg/LineStipple.cpp \
../src/osg/src/osgWrappers/serializers/osg/LineWidth.cpp \
../src/osg/src/osgWrappers/serializers/osg/LogicOp.cpp \
../src/osg/src/osgWrappers/serializers/osg/Material.cpp \
../src/osg/src/osgWrappers/serializers/osg/MatrixTransform.cpp \
../src/osg/src/osgWrappers/serializers/osg/Multisample.cpp \
../src/osg/src/osgWrappers/serializers/osg/Node.cpp \
../src/osg/src/osgWrappers/serializers/osg/NodeCallback.cpp \
../src/osg/src/osgWrappers/serializers/osg/NodeTrackerCallback.cpp \
../src/osg/src/osgWrappers/serializers/osg/NodeVisitor.cpp \
../src/osg/src/osgWrappers/serializers/osg/Object.cpp \
../src/osg/src/osgWrappers/serializers/osg/OccluderNode.cpp \
../src/osg/src/osgWrappers/serializers/osg/OcclusionQueryNode.cpp \
../src/osg/src/osgWrappers/serializers/osg/PagedLOD.cpp \
../src/osg/src/osgWrappers/serializers/osg/PatchParameter.cpp \
../src/osg/src/osgWrappers/serializers/osg/Point.cpp \
../src/osg/src/osgWrappers/serializers/osg/PointSprite.cpp \
../src/osg/src/osgWrappers/serializers/osg/PolygonMode.cpp \
../src/osg/src/osgWrappers/serializers/osg/PolygonOffset.cpp \
../src/osg/src/osgWrappers/serializers/osg/PolygonStipple.cpp \
../src/osg/src/osgWrappers/serializers/osg/PositionAttitudeTransform.cpp \
../src/osg/src/osgWrappers/serializers/osg/PrimitiveRestartIndex.cpp \
../src/osg/src/osgWrappers/serializers/osg/PrimitiveSet.cpp \
../src/osg/src/osgWrappers/serializers/osg/Program.cpp \
../src/osg/src/osgWrappers/serializers/osg/Projection.cpp \
../src/osg/src/osgWrappers/serializers/osg/ProxyNode.cpp \
../src/osg/src/osgWrappers/serializers/osg/SampleMaski.cpp \
../src/osg/src/osgWrappers/serializers/osg/Scissor.cpp \
../src/osg/src/osgWrappers/serializers/osg/Sequence.cpp \
../src/osg/src/osgWrappers/serializers/osg/ShadeModel.cpp \
../src/osg/src/osgWrappers/serializers/osg/Shader.cpp \
../src/osg/src/osgWrappers/serializers/osg/ShaderBinary.cpp \
../src/osg/src/osgWrappers/serializers/osg/Shape.cpp \
../src/osg/src/osgWrappers/serializers/osg/ShapeDrawable.cpp \
../src/osg/src/osgWrappers/serializers/osg/Sphere.cpp \
../src/osg/src/osgWrappers/serializers/osg/StateAttribute.cpp \
../src/osg/src/osgWrappers/serializers/osg/StateSet.cpp \
../src/osg/src/osgWrappers/serializers/osg/Stencil.cpp \
../src/osg/src/osgWrappers/serializers/osg/StencilTwoSided.cpp \
../src/osg/src/osgWrappers/serializers/osg/Switch.cpp \
../src/osg/src/osgWrappers/serializers/osg/TessellationHints.cpp \
../src/osg/src/osgWrappers/serializers/osg/TexEnv.cpp \
../src/osg/src/osgWrappers/serializers/osg/TexEnvCombine.cpp \
../src/osg/src/osgWrappers/serializers/osg/TexEnvFilter.cpp \
../src/osg/src/osgWrappers/serializers/osg/TexGen.cpp \
../src/osg/src/osgWrappers/serializers/osg/TexGenNode.cpp \
../src/osg/src/osgWrappers/serializers/osg/TexMat.cpp \
../src/osg/src/osgWrappers/serializers/osg/Texture.cpp \
../src/osg/src/osgWrappers/serializers/osg/Texture1D.cpp \
../src/osg/src/osgWrappers/serializers/osg/Texture2D.cpp \
../src/osg/src/osgWrappers/serializers/osg/Texture2DArray.cpp \
../src/osg/src/osgWrappers/serializers/osg/Texture3D.cpp \
../src/osg/src/osgWrappers/serializers/osg/TextureCubeMap.cpp \
../src/osg/src/osgWrappers/serializers/osg/TextureRectangle.cpp \
../src/osg/src/osgWrappers/serializers/osg/TransferFunction.cpp \
../src/osg/src/osgWrappers/serializers/osg/TransferFunction1D.cpp \
../src/osg/src/osgWrappers/serializers/osg/Transform.cpp \
../src/osg/src/osgWrappers/serializers/osg/TriangleMesh.cpp \
../src/osg/src/osgWrappers/serializers/osg/Uniform.cpp \
../src/osg/src/osgWrappers/serializers/osg/UpdateCallback.cpp \
../src/osg/src/osgWrappers/serializers/osg/UserDataContainer.cpp \
../src/osg/src/osgWrappers/serializers/osg/ValueObject.cpp \
../src/osg/src/osgWrappers/serializers/osg/VertexAttribDivisor.cpp \
../src/osg/src/osgWrappers/serializers/osg/VertexProgram.cpp \
../src/osg/src/osgWrappers/serializers/osg/Viewport.cpp 

OBJS += \
./src/osg/src/osgWrappers/serializers/osg/AlphaFunc.o \
./src/osg/src/osgWrappers/serializers/osg/AnimationPath.o \
./src/osg/src/osgWrappers/serializers/osg/AnimationPathCallback.o \
./src/osg/src/osgWrappers/serializers/osg/Array.o \
./src/osg/src/osgWrappers/serializers/osg/AudioSink.o \
./src/osg/src/osgWrappers/serializers/osg/AudioStream.o \
./src/osg/src/osgWrappers/serializers/osg/AutoTransform.o \
./src/osg/src/osgWrappers/serializers/osg/Billboard.o \
./src/osg/src/osgWrappers/serializers/osg/BlendColor.o \
./src/osg/src/osgWrappers/serializers/osg/BlendEquation.o \
./src/osg/src/osgWrappers/serializers/osg/BlendEquationi.o \
./src/osg/src/osgWrappers/serializers/osg/BlendFunc.o \
./src/osg/src/osgWrappers/serializers/osg/BlendFunci.o \
./src/osg/src/osgWrappers/serializers/osg/Box.o \
./src/osg/src/osgWrappers/serializers/osg/Callback.o \
./src/osg/src/osgWrappers/serializers/osg/Camera.o \
./src/osg/src/osgWrappers/serializers/osg/CameraView.o \
./src/osg/src/osgWrappers/serializers/osg/Capsule.o \
./src/osg/src/osgWrappers/serializers/osg/ClampColor.o \
./src/osg/src/osgWrappers/serializers/osg/ClearNode.o \
./src/osg/src/osgWrappers/serializers/osg/ClipNode.o \
./src/osg/src/osgWrappers/serializers/osg/ClipPlane.o \
./src/osg/src/osgWrappers/serializers/osg/ClusterCullingCallback.o \
./src/osg/src/osgWrappers/serializers/osg/ColorMask.o \
./src/osg/src/osgWrappers/serializers/osg/ColorMaski.o \
./src/osg/src/osgWrappers/serializers/osg/ColorMatrix.o \
./src/osg/src/osgWrappers/serializers/osg/CompositeShape.o \
./src/osg/src/osgWrappers/serializers/osg/ComputeBoundingBoxCallback.o \
./src/osg/src/osgWrappers/serializers/osg/Cone.o \
./src/osg/src/osgWrappers/serializers/osg/ConvexHull.o \
./src/osg/src/osgWrappers/serializers/osg/ConvexPlanarOccluder.o \
./src/osg/src/osgWrappers/serializers/osg/CoordinateSystemNode.o \
./src/osg/src/osgWrappers/serializers/osg/CullFace.o \
./src/osg/src/osgWrappers/serializers/osg/Cylinder.o \
./src/osg/src/osgWrappers/serializers/osg/Depth.o \
./src/osg/src/osgWrappers/serializers/osg/DrawPixels.o \
./src/osg/src/osgWrappers/serializers/osg/Drawable.o \
./src/osg/src/osgWrappers/serializers/osg/EllipsoidModel.o \
./src/osg/src/osgWrappers/serializers/osg/Fog.o \
./src/osg/src/osgWrappers/serializers/osg/FragmentProgram.o \
./src/osg/src/osgWrappers/serializers/osg/FrontFace.o \
./src/osg/src/osgWrappers/serializers/osg/Geode.o \
./src/osg/src/osgWrappers/serializers/osg/Geometry.o \
./src/osg/src/osgWrappers/serializers/osg/Group.o \
./src/osg/src/osgWrappers/serializers/osg/HeightField.o \
./src/osg/src/osgWrappers/serializers/osg/Hint.o \
./src/osg/src/osgWrappers/serializers/osg/Image.o \
./src/osg/src/osgWrappers/serializers/osg/ImageSequence.o \
./src/osg/src/osgWrappers/serializers/osg/ImageStream.o \
./src/osg/src/osgWrappers/serializers/osg/LOD.o \
./src/osg/src/osgWrappers/serializers/osg/LibraryWrapper.o \
./src/osg/src/osgWrappers/serializers/osg/Light.o \
./src/osg/src/osgWrappers/serializers/osg/LightModel.o \
./src/osg/src/osgWrappers/serializers/osg/LightSource.o \
./src/osg/src/osgWrappers/serializers/osg/LineStipple.o \
./src/osg/src/osgWrappers/serializers/osg/LineWidth.o \
./src/osg/src/osgWrappers/serializers/osg/LogicOp.o \
./src/osg/src/osgWrappers/serializers/osg/Material.o \
./src/osg/src/osgWrappers/serializers/osg/MatrixTransform.o \
./src/osg/src/osgWrappers/serializers/osg/Multisample.o \
./src/osg/src/osgWrappers/serializers/osg/Node.o \
./src/osg/src/osgWrappers/serializers/osg/NodeCallback.o \
./src/osg/src/osgWrappers/serializers/osg/NodeTrackerCallback.o \
./src/osg/src/osgWrappers/serializers/osg/NodeVisitor.o \
./src/osg/src/osgWrappers/serializers/osg/Object.o \
./src/osg/src/osgWrappers/serializers/osg/OccluderNode.o \
./src/osg/src/osgWrappers/serializers/osg/OcclusionQueryNode.o \
./src/osg/src/osgWrappers/serializers/osg/PagedLOD.o \
./src/osg/src/osgWrappers/serializers/osg/PatchParameter.o \
./src/osg/src/osgWrappers/serializers/osg/Point.o \
./src/osg/src/osgWrappers/serializers/osg/PointSprite.o \
./src/osg/src/osgWrappers/serializers/osg/PolygonMode.o \
./src/osg/src/osgWrappers/serializers/osg/PolygonOffset.o \
./src/osg/src/osgWrappers/serializers/osg/PolygonStipple.o \
./src/osg/src/osgWrappers/serializers/osg/PositionAttitudeTransform.o \
./src/osg/src/osgWrappers/serializers/osg/PrimitiveRestartIndex.o \
./src/osg/src/osgWrappers/serializers/osg/PrimitiveSet.o \
./src/osg/src/osgWrappers/serializers/osg/Program.o \
./src/osg/src/osgWrappers/serializers/osg/Projection.o \
./src/osg/src/osgWrappers/serializers/osg/ProxyNode.o \
./src/osg/src/osgWrappers/serializers/osg/SampleMaski.o \
./src/osg/src/osgWrappers/serializers/osg/Scissor.o \
./src/osg/src/osgWrappers/serializers/osg/Sequence.o \
./src/osg/src/osgWrappers/serializers/osg/ShadeModel.o \
./src/osg/src/osgWrappers/serializers/osg/Shader.o \
./src/osg/src/osgWrappers/serializers/osg/ShaderBinary.o \
./src/osg/src/osgWrappers/serializers/osg/Shape.o \
./src/osg/src/osgWrappers/serializers/osg/ShapeDrawable.o \
./src/osg/src/osgWrappers/serializers/osg/Sphere.o \
./src/osg/src/osgWrappers/serializers/osg/StateAttribute.o \
./src/osg/src/osgWrappers/serializers/osg/StateSet.o \
./src/osg/src/osgWrappers/serializers/osg/Stencil.o \
./src/osg/src/osgWrappers/serializers/osg/StencilTwoSided.o \
./src/osg/src/osgWrappers/serializers/osg/Switch.o \
./src/osg/src/osgWrappers/serializers/osg/TessellationHints.o \
./src/osg/src/osgWrappers/serializers/osg/TexEnv.o \
./src/osg/src/osgWrappers/serializers/osg/TexEnvCombine.o \
./src/osg/src/osgWrappers/serializers/osg/TexEnvFilter.o \
./src/osg/src/osgWrappers/serializers/osg/TexGen.o \
./src/osg/src/osgWrappers/serializers/osg/TexGenNode.o \
./src/osg/src/osgWrappers/serializers/osg/TexMat.o \
./src/osg/src/osgWrappers/serializers/osg/Texture.o \
./src/osg/src/osgWrappers/serializers/osg/Texture1D.o \
./src/osg/src/osgWrappers/serializers/osg/Texture2D.o \
./src/osg/src/osgWrappers/serializers/osg/Texture2DArray.o \
./src/osg/src/osgWrappers/serializers/osg/Texture3D.o \
./src/osg/src/osgWrappers/serializers/osg/TextureCubeMap.o \
./src/osg/src/osgWrappers/serializers/osg/TextureRectangle.o \
./src/osg/src/osgWrappers/serializers/osg/TransferFunction.o \
./src/osg/src/osgWrappers/serializers/osg/TransferFunction1D.o \
./src/osg/src/osgWrappers/serializers/osg/Transform.o \
./src/osg/src/osgWrappers/serializers/osg/TriangleMesh.o \
./src/osg/src/osgWrappers/serializers/osg/Uniform.o \
./src/osg/src/osgWrappers/serializers/osg/UpdateCallback.o \
./src/osg/src/osgWrappers/serializers/osg/UserDataContainer.o \
./src/osg/src/osgWrappers/serializers/osg/ValueObject.o \
./src/osg/src/osgWrappers/serializers/osg/VertexAttribDivisor.o \
./src/osg/src/osgWrappers/serializers/osg/VertexProgram.o \
./src/osg/src/osgWrappers/serializers/osg/Viewport.o 

CPP_DEPS += \
./src/osg/src/osgWrappers/serializers/osg/AlphaFunc.d \
./src/osg/src/osgWrappers/serializers/osg/AnimationPath.d \
./src/osg/src/osgWrappers/serializers/osg/AnimationPathCallback.d \
./src/osg/src/osgWrappers/serializers/osg/Array.d \
./src/osg/src/osgWrappers/serializers/osg/AudioSink.d \
./src/osg/src/osgWrappers/serializers/osg/AudioStream.d \
./src/osg/src/osgWrappers/serializers/osg/AutoTransform.d \
./src/osg/src/osgWrappers/serializers/osg/Billboard.d \
./src/osg/src/osgWrappers/serializers/osg/BlendColor.d \
./src/osg/src/osgWrappers/serializers/osg/BlendEquation.d \
./src/osg/src/osgWrappers/serializers/osg/BlendEquationi.d \
./src/osg/src/osgWrappers/serializers/osg/BlendFunc.d \
./src/osg/src/osgWrappers/serializers/osg/BlendFunci.d \
./src/osg/src/osgWrappers/serializers/osg/Box.d \
./src/osg/src/osgWrappers/serializers/osg/Callback.d \
./src/osg/src/osgWrappers/serializers/osg/Camera.d \
./src/osg/src/osgWrappers/serializers/osg/CameraView.d \
./src/osg/src/osgWrappers/serializers/osg/Capsule.d \
./src/osg/src/osgWrappers/serializers/osg/ClampColor.d \
./src/osg/src/osgWrappers/serializers/osg/ClearNode.d \
./src/osg/src/osgWrappers/serializers/osg/ClipNode.d \
./src/osg/src/osgWrappers/serializers/osg/ClipPlane.d \
./src/osg/src/osgWrappers/serializers/osg/ClusterCullingCallback.d \
./src/osg/src/osgWrappers/serializers/osg/ColorMask.d \
./src/osg/src/osgWrappers/serializers/osg/ColorMaski.d \
./src/osg/src/osgWrappers/serializers/osg/ColorMatrix.d \
./src/osg/src/osgWrappers/serializers/osg/CompositeShape.d \
./src/osg/src/osgWrappers/serializers/osg/ComputeBoundingBoxCallback.d \
./src/osg/src/osgWrappers/serializers/osg/Cone.d \
./src/osg/src/osgWrappers/serializers/osg/ConvexHull.d \
./src/osg/src/osgWrappers/serializers/osg/ConvexPlanarOccluder.d \
./src/osg/src/osgWrappers/serializers/osg/CoordinateSystemNode.d \
./src/osg/src/osgWrappers/serializers/osg/CullFace.d \
./src/osg/src/osgWrappers/serializers/osg/Cylinder.d \
./src/osg/src/osgWrappers/serializers/osg/Depth.d \
./src/osg/src/osgWrappers/serializers/osg/DrawPixels.d \
./src/osg/src/osgWrappers/serializers/osg/Drawable.d \
./src/osg/src/osgWrappers/serializers/osg/EllipsoidModel.d \
./src/osg/src/osgWrappers/serializers/osg/Fog.d \
./src/osg/src/osgWrappers/serializers/osg/FragmentProgram.d \
./src/osg/src/osgWrappers/serializers/osg/FrontFace.d \
./src/osg/src/osgWrappers/serializers/osg/Geode.d \
./src/osg/src/osgWrappers/serializers/osg/Geometry.d \
./src/osg/src/osgWrappers/serializers/osg/Group.d \
./src/osg/src/osgWrappers/serializers/osg/HeightField.d \
./src/osg/src/osgWrappers/serializers/osg/Hint.d \
./src/osg/src/osgWrappers/serializers/osg/Image.d \
./src/osg/src/osgWrappers/serializers/osg/ImageSequence.d \
./src/osg/src/osgWrappers/serializers/osg/ImageStream.d \
./src/osg/src/osgWrappers/serializers/osg/LOD.d \
./src/osg/src/osgWrappers/serializers/osg/LibraryWrapper.d \
./src/osg/src/osgWrappers/serializers/osg/Light.d \
./src/osg/src/osgWrappers/serializers/osg/LightModel.d \
./src/osg/src/osgWrappers/serializers/osg/LightSource.d \
./src/osg/src/osgWrappers/serializers/osg/LineStipple.d \
./src/osg/src/osgWrappers/serializers/osg/LineWidth.d \
./src/osg/src/osgWrappers/serializers/osg/LogicOp.d \
./src/osg/src/osgWrappers/serializers/osg/Material.d \
./src/osg/src/osgWrappers/serializers/osg/MatrixTransform.d \
./src/osg/src/osgWrappers/serializers/osg/Multisample.d \
./src/osg/src/osgWrappers/serializers/osg/Node.d \
./src/osg/src/osgWrappers/serializers/osg/NodeCallback.d \
./src/osg/src/osgWrappers/serializers/osg/NodeTrackerCallback.d \
./src/osg/src/osgWrappers/serializers/osg/NodeVisitor.d \
./src/osg/src/osgWrappers/serializers/osg/Object.d \
./src/osg/src/osgWrappers/serializers/osg/OccluderNode.d \
./src/osg/src/osgWrappers/serializers/osg/OcclusionQueryNode.d \
./src/osg/src/osgWrappers/serializers/osg/PagedLOD.d \
./src/osg/src/osgWrappers/serializers/osg/PatchParameter.d \
./src/osg/src/osgWrappers/serializers/osg/Point.d \
./src/osg/src/osgWrappers/serializers/osg/PointSprite.d \
./src/osg/src/osgWrappers/serializers/osg/PolygonMode.d \
./src/osg/src/osgWrappers/serializers/osg/PolygonOffset.d \
./src/osg/src/osgWrappers/serializers/osg/PolygonStipple.d \
./src/osg/src/osgWrappers/serializers/osg/PositionAttitudeTransform.d \
./src/osg/src/osgWrappers/serializers/osg/PrimitiveRestartIndex.d \
./src/osg/src/osgWrappers/serializers/osg/PrimitiveSet.d \
./src/osg/src/osgWrappers/serializers/osg/Program.d \
./src/osg/src/osgWrappers/serializers/osg/Projection.d \
./src/osg/src/osgWrappers/serializers/osg/ProxyNode.d \
./src/osg/src/osgWrappers/serializers/osg/SampleMaski.d \
./src/osg/src/osgWrappers/serializers/osg/Scissor.d \
./src/osg/src/osgWrappers/serializers/osg/Sequence.d \
./src/osg/src/osgWrappers/serializers/osg/ShadeModel.d \
./src/osg/src/osgWrappers/serializers/osg/Shader.d \
./src/osg/src/osgWrappers/serializers/osg/ShaderBinary.d \
./src/osg/src/osgWrappers/serializers/osg/Shape.d \
./src/osg/src/osgWrappers/serializers/osg/ShapeDrawable.d \
./src/osg/src/osgWrappers/serializers/osg/Sphere.d \
./src/osg/src/osgWrappers/serializers/osg/StateAttribute.d \
./src/osg/src/osgWrappers/serializers/osg/StateSet.d \
./src/osg/src/osgWrappers/serializers/osg/Stencil.d \
./src/osg/src/osgWrappers/serializers/osg/StencilTwoSided.d \
./src/osg/src/osgWrappers/serializers/osg/Switch.d \
./src/osg/src/osgWrappers/serializers/osg/TessellationHints.d \
./src/osg/src/osgWrappers/serializers/osg/TexEnv.d \
./src/osg/src/osgWrappers/serializers/osg/TexEnvCombine.d \
./src/osg/src/osgWrappers/serializers/osg/TexEnvFilter.d \
./src/osg/src/osgWrappers/serializers/osg/TexGen.d \
./src/osg/src/osgWrappers/serializers/osg/TexGenNode.d \
./src/osg/src/osgWrappers/serializers/osg/TexMat.d \
./src/osg/src/osgWrappers/serializers/osg/Texture.d \
./src/osg/src/osgWrappers/serializers/osg/Texture1D.d \
./src/osg/src/osgWrappers/serializers/osg/Texture2D.d \
./src/osg/src/osgWrappers/serializers/osg/Texture2DArray.d \
./src/osg/src/osgWrappers/serializers/osg/Texture3D.d \
./src/osg/src/osgWrappers/serializers/osg/TextureCubeMap.d \
./src/osg/src/osgWrappers/serializers/osg/TextureRectangle.d \
./src/osg/src/osgWrappers/serializers/osg/TransferFunction.d \
./src/osg/src/osgWrappers/serializers/osg/TransferFunction1D.d \
./src/osg/src/osgWrappers/serializers/osg/Transform.d \
./src/osg/src/osgWrappers/serializers/osg/TriangleMesh.d \
./src/osg/src/osgWrappers/serializers/osg/Uniform.d \
./src/osg/src/osgWrappers/serializers/osg/UpdateCallback.d \
./src/osg/src/osgWrappers/serializers/osg/UserDataContainer.d \
./src/osg/src/osgWrappers/serializers/osg/ValueObject.d \
./src/osg/src/osgWrappers/serializers/osg/VertexAttribDivisor.d \
./src/osg/src/osgWrappers/serializers/osg/VertexProgram.d \
./src/osg/src/osgWrappers/serializers/osg/Viewport.d 


# Each subdirectory must supply rules for building sources it contributes
src/osg/src/osgWrappers/serializers/osg/%.o: ../src/osg/src/osgWrappers/serializers/osg/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: Cross G++ Compiler'
	g++ -std=c++11 -I/usr/include/gtk-3.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/pixman-1 -I/usr/include/libpng12 -O0 -g3 -Wall -c -fmessage-length=0 `pkg-config --cflags gtk+-3.0` -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


