################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../src/osg/src/osg/AlphaFunc.cpp \
../src/osg/src/osg/AnimationPath.cpp \
../src/osg/src/osg/ApplicationUsage.cpp \
../src/osg/src/osg/ArgumentParser.cpp \
../src/osg/src/osg/Array.cpp \
../src/osg/src/osg/ArrayDispatchers.cpp \
../src/osg/src/osg/AudioStream.cpp \
../src/osg/src/osg/AutoTransform.cpp \
../src/osg/src/osg/Billboard.cpp \
../src/osg/src/osg/BlendColor.cpp \
../src/osg/src/osg/BlendEquation.cpp \
../src/osg/src/osg/BlendEquationi.cpp \
../src/osg/src/osg/BlendFunc.cpp \
../src/osg/src/osg/BlendFunci.cpp \
../src/osg/src/osg/BufferIndexBinding.cpp \
../src/osg/src/osg/BufferObject.cpp \
../src/osg/src/osg/Callback.cpp \
../src/osg/src/osg/Camera.cpp \
../src/osg/src/osg/CameraView.cpp \
../src/osg/src/osg/Capability.cpp \
../src/osg/src/osg/ClampColor.cpp \
../src/osg/src/osg/ClearNode.cpp \
../src/osg/src/osg/ClipNode.cpp \
../src/osg/src/osg/ClipPlane.cpp \
../src/osg/src/osg/ClusterCullingCallback.cpp \
../src/osg/src/osg/CollectOccludersVisitor.cpp \
../src/osg/src/osg/ColorMask.cpp \
../src/osg/src/osg/ColorMaski.cpp \
../src/osg/src/osg/ColorMatrix.cpp \
../src/osg/src/osg/ComputeBoundsVisitor.cpp \
../src/osg/src/osg/ConvexPlanarOccluder.cpp \
../src/osg/src/osg/ConvexPlanarPolygon.cpp \
../src/osg/src/osg/CoordinateSystemNode.cpp \
../src/osg/src/osg/CopyOp.cpp \
../src/osg/src/osg/CullFace.cpp \
../src/osg/src/osg/CullSettings.cpp \
../src/osg/src/osg/CullStack.cpp \
../src/osg/src/osg/CullingSet.cpp \
../src/osg/src/osg/DeleteHandler.cpp \
../src/osg/src/osg/Depth.cpp \
../src/osg/src/osg/DisplaySettings.cpp \
../src/osg/src/osg/DrawPixels.cpp \
../src/osg/src/osg/Drawable.cpp \
../src/osg/src/osg/Fog.cpp \
../src/osg/src/osg/FragmentProgram.cpp \
../src/osg/src/osg/FrameBufferObject.cpp \
../src/osg/src/osg/FrameStamp.cpp \
../src/osg/src/osg/FrontFace.cpp \
../src/osg/src/osg/GLBeginEndAdapter.cpp \
../src/osg/src/osg/GLExtensions.cpp \
../src/osg/src/osg/GLObjects.cpp \
../src/osg/src/osg/GLStaticLibrary.cpp \
../src/osg/src/osg/Geode.cpp \
../src/osg/src/osg/Geometry.cpp \
../src/osg/src/osg/GraphicsContext.cpp \
../src/osg/src/osg/GraphicsCostEstimator.cpp \
../src/osg/src/osg/GraphicsThread.cpp \
../src/osg/src/osg/Group.cpp \
../src/osg/src/osg/Hint.cpp \
../src/osg/src/osg/Image.cpp \
../src/osg/src/osg/ImageSequence.cpp \
../src/osg/src/osg/ImageStream.cpp \
../src/osg/src/osg/ImageUtils.cpp \
../src/osg/src/osg/KdTree.cpp \
../src/osg/src/osg/LOD.cpp \
../src/osg/src/osg/Light.cpp \
../src/osg/src/osg/LightModel.cpp \
../src/osg/src/osg/LightSource.cpp \
../src/osg/src/osg/LineSegment.cpp \
../src/osg/src/osg/LineStipple.cpp \
../src/osg/src/osg/LineWidth.cpp \
../src/osg/src/osg/LogicOp.cpp \
../src/osg/src/osg/Material.cpp \
../src/osg/src/osg/Math.cpp \
../src/osg/src/osg/MatrixDecomposition.cpp \
../src/osg/src/osg/MatrixTransform.cpp \
../src/osg/src/osg/Matrix_implementation.cpp \
../src/osg/src/osg/Matrixd.cpp \
../src/osg/src/osg/Matrixf.cpp \
../src/osg/src/osg/Multisample.cpp \
../src/osg/src/osg/Node.cpp \
../src/osg/src/osg/NodeTrackerCallback.cpp \
../src/osg/src/osg/NodeVisitor.cpp \
../src/osg/src/osg/Notify.cpp \
../src/osg/src/osg/Object.cpp \
../src/osg/src/osg/Observer.cpp \
../src/osg/src/osg/ObserverNodePath.cpp \
../src/osg/src/osg/OccluderNode.cpp \
../src/osg/src/osg/OcclusionQueryNode.cpp \
../src/osg/src/osg/OperationThread.cpp \
../src/osg/src/osg/PagedLOD.cpp \
../src/osg/src/osg/PatchParameter.cpp \
../src/osg/src/osg/Point.cpp \
../src/osg/src/osg/PointSprite.cpp \
../src/osg/src/osg/PolygonMode.cpp \
../src/osg/src/osg/PolygonOffset.cpp \
../src/osg/src/osg/PolygonStipple.cpp \
../src/osg/src/osg/PositionAttitudeTransform.cpp \
../src/osg/src/osg/PrimitiveRestartIndex.cpp \
../src/osg/src/osg/PrimitiveSet.cpp \
../src/osg/src/osg/Program.cpp \
../src/osg/src/osg/Projection.cpp \
../src/osg/src/osg/ProxyNode.cpp \
../src/osg/src/osg/Quat.cpp \
../src/osg/src/osg/Referenced.cpp \
../src/osg/src/osg/SampleMaski.cpp \
../src/osg/src/osg/Scissor.cpp \
../src/osg/src/osg/ScriptEngine.cpp \
../src/osg/src/osg/Sequence.cpp \
../src/osg/src/osg/ShadeModel.cpp \
../src/osg/src/osg/Shader.cpp \
../src/osg/src/osg/ShaderAttribute.cpp \
../src/osg/src/osg/ShaderComposer.cpp \
../src/osg/src/osg/ShadowVolumeOccluder.cpp \
../src/osg/src/osg/Shape.cpp \
../src/osg/src/osg/ShapeDrawable.cpp \
../src/osg/src/osg/State.cpp \
../src/osg/src/osg/StateAttribute.cpp \
../src/osg/src/osg/StateSet.cpp \
../src/osg/src/osg/Stats.cpp \
../src/osg/src/osg/Stencil.cpp \
../src/osg/src/osg/StencilTwoSided.cpp \
../src/osg/src/osg/Switch.cpp \
../src/osg/src/osg/TexEnv.cpp \
../src/osg/src/osg/TexEnvCombine.cpp \
../src/osg/src/osg/TexEnvFilter.cpp \
../src/osg/src/osg/TexGen.cpp \
../src/osg/src/osg/TexGenNode.cpp \
../src/osg/src/osg/TexMat.cpp \
../src/osg/src/osg/Texture.cpp \
../src/osg/src/osg/Texture1D.cpp \
../src/osg/src/osg/Texture2D.cpp \
../src/osg/src/osg/Texture2DArray.cpp \
../src/osg/src/osg/Texture2DMultisample.cpp \
../src/osg/src/osg/Texture3D.cpp \
../src/osg/src/osg/TextureBuffer.cpp \
../src/osg/src/osg/TextureCubeMap.cpp \
../src/osg/src/osg/TextureRectangle.cpp \
../src/osg/src/osg/Timer.cpp \
../src/osg/src/osg/TransferFunction.cpp \
../src/osg/src/osg/Transform.cpp \
../src/osg/src/osg/Uniform.cpp \
../src/osg/src/osg/UserDataContainer.cpp \
../src/osg/src/osg/Version.cpp \
../src/osg/src/osg/VertexAttribDivisor.cpp \
../src/osg/src/osg/VertexProgram.cpp \
../src/osg/src/osg/View.cpp \
../src/osg/src/osg/Viewport.cpp \
../src/osg/src/osg/dxtctool.cpp 

OBJS += \
./src/osg/src/osg/AlphaFunc.o \
./src/osg/src/osg/AnimationPath.o \
./src/osg/src/osg/ApplicationUsage.o \
./src/osg/src/osg/ArgumentParser.o \
./src/osg/src/osg/Array.o \
./src/osg/src/osg/ArrayDispatchers.o \
./src/osg/src/osg/AudioStream.o \
./src/osg/src/osg/AutoTransform.o \
./src/osg/src/osg/Billboard.o \
./src/osg/src/osg/BlendColor.o \
./src/osg/src/osg/BlendEquation.o \
./src/osg/src/osg/BlendEquationi.o \
./src/osg/src/osg/BlendFunc.o \
./src/osg/src/osg/BlendFunci.o \
./src/osg/src/osg/BufferIndexBinding.o \
./src/osg/src/osg/BufferObject.o \
./src/osg/src/osg/Callback.o \
./src/osg/src/osg/Camera.o \
./src/osg/src/osg/CameraView.o \
./src/osg/src/osg/Capability.o \
./src/osg/src/osg/ClampColor.o \
./src/osg/src/osg/ClearNode.o \
./src/osg/src/osg/ClipNode.o \
./src/osg/src/osg/ClipPlane.o \
./src/osg/src/osg/ClusterCullingCallback.o \
./src/osg/src/osg/CollectOccludersVisitor.o \
./src/osg/src/osg/ColorMask.o \
./src/osg/src/osg/ColorMaski.o \
./src/osg/src/osg/ColorMatrix.o \
./src/osg/src/osg/ComputeBoundsVisitor.o \
./src/osg/src/osg/ConvexPlanarOccluder.o \
./src/osg/src/osg/ConvexPlanarPolygon.o \
./src/osg/src/osg/CoordinateSystemNode.o \
./src/osg/src/osg/CopyOp.o \
./src/osg/src/osg/CullFace.o \
./src/osg/src/osg/CullSettings.o \
./src/osg/src/osg/CullStack.o \
./src/osg/src/osg/CullingSet.o \
./src/osg/src/osg/DeleteHandler.o \
./src/osg/src/osg/Depth.o \
./src/osg/src/osg/DisplaySettings.o \
./src/osg/src/osg/DrawPixels.o \
./src/osg/src/osg/Drawable.o \
./src/osg/src/osg/Fog.o \
./src/osg/src/osg/FragmentProgram.o \
./src/osg/src/osg/FrameBufferObject.o \
./src/osg/src/osg/FrameStamp.o \
./src/osg/src/osg/FrontFace.o \
./src/osg/src/osg/GLBeginEndAdapter.o \
./src/osg/src/osg/GLExtensions.o \
./src/osg/src/osg/GLObjects.o \
./src/osg/src/osg/GLStaticLibrary.o \
./src/osg/src/osg/Geode.o \
./src/osg/src/osg/Geometry.o \
./src/osg/src/osg/GraphicsContext.o \
./src/osg/src/osg/GraphicsCostEstimator.o \
./src/osg/src/osg/GraphicsThread.o \
./src/osg/src/osg/Group.o \
./src/osg/src/osg/Hint.o \
./src/osg/src/osg/Image.o \
./src/osg/src/osg/ImageSequence.o \
./src/osg/src/osg/ImageStream.o \
./src/osg/src/osg/ImageUtils.o \
./src/osg/src/osg/KdTree.o \
./src/osg/src/osg/LOD.o \
./src/osg/src/osg/Light.o \
./src/osg/src/osg/LightModel.o \
./src/osg/src/osg/LightSource.o \
./src/osg/src/osg/LineSegment.o \
./src/osg/src/osg/LineStipple.o \
./src/osg/src/osg/LineWidth.o \
./src/osg/src/osg/LogicOp.o \
./src/osg/src/osg/Material.o \
./src/osg/src/osg/Math.o \
./src/osg/src/osg/MatrixDecomposition.o \
./src/osg/src/osg/MatrixTransform.o \
./src/osg/src/osg/Matrix_implementation.o \
./src/osg/src/osg/Matrixd.o \
./src/osg/src/osg/Matrixf.o \
./src/osg/src/osg/Multisample.o \
./src/osg/src/osg/Node.o \
./src/osg/src/osg/NodeTrackerCallback.o \
./src/osg/src/osg/NodeVisitor.o \
./src/osg/src/osg/Notify.o \
./src/osg/src/osg/Object.o \
./src/osg/src/osg/Observer.o \
./src/osg/src/osg/ObserverNodePath.o \
./src/osg/src/osg/OccluderNode.o \
./src/osg/src/osg/OcclusionQueryNode.o \
./src/osg/src/osg/OperationThread.o \
./src/osg/src/osg/PagedLOD.o \
./src/osg/src/osg/PatchParameter.o \
./src/osg/src/osg/Point.o \
./src/osg/src/osg/PointSprite.o \
./src/osg/src/osg/PolygonMode.o \
./src/osg/src/osg/PolygonOffset.o \
./src/osg/src/osg/PolygonStipple.o \
./src/osg/src/osg/PositionAttitudeTransform.o \
./src/osg/src/osg/PrimitiveRestartIndex.o \
./src/osg/src/osg/PrimitiveSet.o \
./src/osg/src/osg/Program.o \
./src/osg/src/osg/Projection.o \
./src/osg/src/osg/ProxyNode.o \
./src/osg/src/osg/Quat.o \
./src/osg/src/osg/Referenced.o \
./src/osg/src/osg/SampleMaski.o \
./src/osg/src/osg/Scissor.o \
./src/osg/src/osg/ScriptEngine.o \
./src/osg/src/osg/Sequence.o \
./src/osg/src/osg/ShadeModel.o \
./src/osg/src/osg/Shader.o \
./src/osg/src/osg/ShaderAttribute.o \
./src/osg/src/osg/ShaderComposer.o \
./src/osg/src/osg/ShadowVolumeOccluder.o \
./src/osg/src/osg/Shape.o \
./src/osg/src/osg/ShapeDrawable.o \
./src/osg/src/osg/State.o \
./src/osg/src/osg/StateAttribute.o \
./src/osg/src/osg/StateSet.o \
./src/osg/src/osg/Stats.o \
./src/osg/src/osg/Stencil.o \
./src/osg/src/osg/StencilTwoSided.o \
./src/osg/src/osg/Switch.o \
./src/osg/src/osg/TexEnv.o \
./src/osg/src/osg/TexEnvCombine.o \
./src/osg/src/osg/TexEnvFilter.o \
./src/osg/src/osg/TexGen.o \
./src/osg/src/osg/TexGenNode.o \
./src/osg/src/osg/TexMat.o \
./src/osg/src/osg/Texture.o \
./src/osg/src/osg/Texture1D.o \
./src/osg/src/osg/Texture2D.o \
./src/osg/src/osg/Texture2DArray.o \
./src/osg/src/osg/Texture2DMultisample.o \
./src/osg/src/osg/Texture3D.o \
./src/osg/src/osg/TextureBuffer.o \
./src/osg/src/osg/TextureCubeMap.o \
./src/osg/src/osg/TextureRectangle.o \
./src/osg/src/osg/Timer.o \
./src/osg/src/osg/TransferFunction.o \
./src/osg/src/osg/Transform.o \
./src/osg/src/osg/Uniform.o \
./src/osg/src/osg/UserDataContainer.o \
./src/osg/src/osg/Version.o \
./src/osg/src/osg/VertexAttribDivisor.o \
./src/osg/src/osg/VertexProgram.o \
./src/osg/src/osg/View.o \
./src/osg/src/osg/Viewport.o \
./src/osg/src/osg/dxtctool.o 

CPP_DEPS += \
./src/osg/src/osg/AlphaFunc.d \
./src/osg/src/osg/AnimationPath.d \
./src/osg/src/osg/ApplicationUsage.d \
./src/osg/src/osg/ArgumentParser.d \
./src/osg/src/osg/Array.d \
./src/osg/src/osg/ArrayDispatchers.d \
./src/osg/src/osg/AudioStream.d \
./src/osg/src/osg/AutoTransform.d \
./src/osg/src/osg/Billboard.d \
./src/osg/src/osg/BlendColor.d \
./src/osg/src/osg/BlendEquation.d \
./src/osg/src/osg/BlendEquationi.d \
./src/osg/src/osg/BlendFunc.d \
./src/osg/src/osg/BlendFunci.d \
./src/osg/src/osg/BufferIndexBinding.d \
./src/osg/src/osg/BufferObject.d \
./src/osg/src/osg/Callback.d \
./src/osg/src/osg/Camera.d \
./src/osg/src/osg/CameraView.d \
./src/osg/src/osg/Capability.d \
./src/osg/src/osg/ClampColor.d \
./src/osg/src/osg/ClearNode.d \
./src/osg/src/osg/ClipNode.d \
./src/osg/src/osg/ClipPlane.d \
./src/osg/src/osg/ClusterCullingCallback.d \
./src/osg/src/osg/CollectOccludersVisitor.d \
./src/osg/src/osg/ColorMask.d \
./src/osg/src/osg/ColorMaski.d \
./src/osg/src/osg/ColorMatrix.d \
./src/osg/src/osg/ComputeBoundsVisitor.d \
./src/osg/src/osg/ConvexPlanarOccluder.d \
./src/osg/src/osg/ConvexPlanarPolygon.d \
./src/osg/src/osg/CoordinateSystemNode.d \
./src/osg/src/osg/CopyOp.d \
./src/osg/src/osg/CullFace.d \
./src/osg/src/osg/CullSettings.d \
./src/osg/src/osg/CullStack.d \
./src/osg/src/osg/CullingSet.d \
./src/osg/src/osg/DeleteHandler.d \
./src/osg/src/osg/Depth.d \
./src/osg/src/osg/DisplaySettings.d \
./src/osg/src/osg/DrawPixels.d \
./src/osg/src/osg/Drawable.d \
./src/osg/src/osg/Fog.d \
./src/osg/src/osg/FragmentProgram.d \
./src/osg/src/osg/FrameBufferObject.d \
./src/osg/src/osg/FrameStamp.d \
./src/osg/src/osg/FrontFace.d \
./src/osg/src/osg/GLBeginEndAdapter.d \
./src/osg/src/osg/GLExtensions.d \
./src/osg/src/osg/GLObjects.d \
./src/osg/src/osg/GLStaticLibrary.d \
./src/osg/src/osg/Geode.d \
./src/osg/src/osg/Geometry.d \
./src/osg/src/osg/GraphicsContext.d \
./src/osg/src/osg/GraphicsCostEstimator.d \
./src/osg/src/osg/GraphicsThread.d \
./src/osg/src/osg/Group.d \
./src/osg/src/osg/Hint.d \
./src/osg/src/osg/Image.d \
./src/osg/src/osg/ImageSequence.d \
./src/osg/src/osg/ImageStream.d \
./src/osg/src/osg/ImageUtils.d \
./src/osg/src/osg/KdTree.d \
./src/osg/src/osg/LOD.d \
./src/osg/src/osg/Light.d \
./src/osg/src/osg/LightModel.d \
./src/osg/src/osg/LightSource.d \
./src/osg/src/osg/LineSegment.d \
./src/osg/src/osg/LineStipple.d \
./src/osg/src/osg/LineWidth.d \
./src/osg/src/osg/LogicOp.d \
./src/osg/src/osg/Material.d \
./src/osg/src/osg/Math.d \
./src/osg/src/osg/MatrixDecomposition.d \
./src/osg/src/osg/MatrixTransform.d \
./src/osg/src/osg/Matrix_implementation.d \
./src/osg/src/osg/Matrixd.d \
./src/osg/src/osg/Matrixf.d \
./src/osg/src/osg/Multisample.d \
./src/osg/src/osg/Node.d \
./src/osg/src/osg/NodeTrackerCallback.d \
./src/osg/src/osg/NodeVisitor.d \
./src/osg/src/osg/Notify.d \
./src/osg/src/osg/Object.d \
./src/osg/src/osg/Observer.d \
./src/osg/src/osg/ObserverNodePath.d \
./src/osg/src/osg/OccluderNode.d \
./src/osg/src/osg/OcclusionQueryNode.d \
./src/osg/src/osg/OperationThread.d \
./src/osg/src/osg/PagedLOD.d \
./src/osg/src/osg/PatchParameter.d \
./src/osg/src/osg/Point.d \
./src/osg/src/osg/PointSprite.d \
./src/osg/src/osg/PolygonMode.d \
./src/osg/src/osg/PolygonOffset.d \
./src/osg/src/osg/PolygonStipple.d \
./src/osg/src/osg/PositionAttitudeTransform.d \
./src/osg/src/osg/PrimitiveRestartIndex.d \
./src/osg/src/osg/PrimitiveSet.d \
./src/osg/src/osg/Program.d \
./src/osg/src/osg/Projection.d \
./src/osg/src/osg/ProxyNode.d \
./src/osg/src/osg/Quat.d \
./src/osg/src/osg/Referenced.d \
./src/osg/src/osg/SampleMaski.d \
./src/osg/src/osg/Scissor.d \
./src/osg/src/osg/ScriptEngine.d \
./src/osg/src/osg/Sequence.d \
./src/osg/src/osg/ShadeModel.d \
./src/osg/src/osg/Shader.d \
./src/osg/src/osg/ShaderAttribute.d \
./src/osg/src/osg/ShaderComposer.d \
./src/osg/src/osg/ShadowVolumeOccluder.d \
./src/osg/src/osg/Shape.d \
./src/osg/src/osg/ShapeDrawable.d \
./src/osg/src/osg/State.d \
./src/osg/src/osg/StateAttribute.d \
./src/osg/src/osg/StateSet.d \
./src/osg/src/osg/Stats.d \
./src/osg/src/osg/Stencil.d \
./src/osg/src/osg/StencilTwoSided.d \
./src/osg/src/osg/Switch.d \
./src/osg/src/osg/TexEnv.d \
./src/osg/src/osg/TexEnvCombine.d \
./src/osg/src/osg/TexEnvFilter.d \
./src/osg/src/osg/TexGen.d \
./src/osg/src/osg/TexGenNode.d \
./src/osg/src/osg/TexMat.d \
./src/osg/src/osg/Texture.d \
./src/osg/src/osg/Texture1D.d \
./src/osg/src/osg/Texture2D.d \
./src/osg/src/osg/Texture2DArray.d \
./src/osg/src/osg/Texture2DMultisample.d \
./src/osg/src/osg/Texture3D.d \
./src/osg/src/osg/TextureBuffer.d \
./src/osg/src/osg/TextureCubeMap.d \
./src/osg/src/osg/TextureRectangle.d \
./src/osg/src/osg/Timer.d \
./src/osg/src/osg/TransferFunction.d \
./src/osg/src/osg/Transform.d \
./src/osg/src/osg/Uniform.d \
./src/osg/src/osg/UserDataContainer.d \
./src/osg/src/osg/Version.d \
./src/osg/src/osg/VertexAttribDivisor.d \
./src/osg/src/osg/VertexProgram.d \
./src/osg/src/osg/View.d \
./src/osg/src/osg/Viewport.d \
./src/osg/src/osg/dxtctool.d 


# Each subdirectory must supply rules for building sources it contributes
src/osg/src/osg/%.o: ../src/osg/src/osg/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: Cross G++ Compiler'
	g++ -std=c++11 -I/usr/include/gtk-3.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/pixman-1 -I/usr/include/libpng12 -O0 -g3 -Wall -c -fmessage-length=0 `pkg-config --cflags gtk+-3.0` -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


