################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/gtk+/tests/animated-resizing.c \
../src/gtk+/tests/animated-revealing.c \
../src/gtk+/tests/flicker.c \
../src/gtk+/tests/frame-stats.c \
../src/gtk+/tests/gdkgears.c \
../src/gtk+/tests/gtkgears.c \
../src/gtk+/tests/gtkoffscreenbox.c \
../src/gtk+/tests/motion-compression.c \
../src/gtk+/tests/overlayscroll.c \
../src/gtk+/tests/print-editor.c \
../src/gtk+/tests/scrolling-performance.c \
../src/gtk+/tests/simple.c \
../src/gtk+/tests/stresstest-toolbar.c \
../src/gtk+/tests/styleexamples.c \
../src/gtk+/tests/subsurface.c \
../src/gtk+/tests/syncscroll.c \
../src/gtk+/tests/testaccel.c \
../src/gtk+/tests/testactionbar.c \
../src/gtk+/tests/testactions.c \
../src/gtk+/tests/testadjustsize.c \
../src/gtk+/tests/testanimation.c \
../src/gtk+/tests/testappchooser.c \
../src/gtk+/tests/testappchooserbutton.c \
../src/gtk+/tests/testassistant.c \
../src/gtk+/tests/testbaseline.c \
../src/gtk+/tests/testbbox.c \
../src/gtk+/tests/testbox.c \
../src/gtk+/tests/testboxcss.c \
../src/gtk+/tests/testbuttons.c \
../src/gtk+/tests/testcairo.c \
../src/gtk+/tests/testcalendar.c \
../src/gtk+/tests/testcellarea.c \
../src/gtk+/tests/testcellrenderertext.c \
../src/gtk+/tests/testclipboard.c \
../src/gtk+/tests/testcolorchooser.c \
../src/gtk+/tests/testcombo.c \
../src/gtk+/tests/testcombochange.c \
../src/gtk+/tests/testdialog.c \
../src/gtk+/tests/testdnd.c \
../src/gtk+/tests/testellipsise.c \
../src/gtk+/tests/testemblems.c \
../src/gtk+/tests/testentrycompletion.c \
../src/gtk+/tests/testentryicons.c \
../src/gtk+/tests/testerrors.c \
../src/gtk+/tests/testexpand.c \
../src/gtk+/tests/testexpander.c \
../src/gtk+/tests/testfilechooser.c \
../src/gtk+/tests/testfilechooserbutton.c \
../src/gtk+/tests/testflowbox.c \
../src/gtk+/tests/testfontchooser.c \
../src/gtk+/tests/testfontchooserdialog.c \
../src/gtk+/tests/testfontselection.c \
../src/gtk+/tests/testfontselectiondialog.c \
../src/gtk+/tests/testframe.c \
../src/gtk+/tests/testfullscreen.c \
../src/gtk+/tests/testgeometry.c \
../src/gtk+/tests/testgiconpixbuf.c \
../src/gtk+/tests/testglarea.c \
../src/gtk+/tests/testglblending.c \
../src/gtk+/tests/testgmenu.c \
../src/gtk+/tests/testgrid.c \
../src/gtk+/tests/testgrouping.c \
../src/gtk+/tests/testgtk.c \
../src/gtk+/tests/testheaderbar.c \
../src/gtk+/tests/testheightforwidth.c \
../src/gtk+/tests/testicontheme.c \
../src/gtk+/tests/testiconview-keynav.c \
../src/gtk+/tests/testiconview.c \
../src/gtk+/tests/testimage.c \
../src/gtk+/tests/testinput.c \
../src/gtk+/tests/testkineticscrolling.c \
../src/gtk+/tests/testlevelbar.c \
../src/gtk+/tests/testlist.c \
../src/gtk+/tests/testlist2.c \
../src/gtk+/tests/testlist3.c \
../src/gtk+/tests/testlockbutton.c \
../src/gtk+/tests/testlogout.c \
../src/gtk+/tests/testmenubutton.c \
../src/gtk+/tests/testmerge.c \
../src/gtk+/tests/testmountoperation.c \
../src/gtk+/tests/testmultidisplay.c \
../src/gtk+/tests/testnoscreen.c \
../src/gtk+/tests/testnotebookdnd.c \
../src/gtk+/tests/testnouiprint.c \
../src/gtk+/tests/testnumerableicon.c \
../src/gtk+/tests/testoffscreen.c \
../src/gtk+/tests/testoffscreenwindow.c \
../src/gtk+/tests/testorientable.c \
../src/gtk+/tests/testoverlay.c \
../src/gtk+/tests/testoverlaystyleclass.c \
../src/gtk+/tests/testpixbuf-color.c \
../src/gtk+/tests/testpixbuf-save.c \
../src/gtk+/tests/testpixbuf-scale.c \
../src/gtk+/tests/testpopover.c \
../src/gtk+/tests/testprint.c \
../src/gtk+/tests/testprintfileoperation.c \
../src/gtk+/tests/testrc.c \
../src/gtk+/tests/testrecentchooser.c \
../src/gtk+/tests/testrecentchoosermenu.c \
../src/gtk+/tests/testrevealer.c \
../src/gtk+/tests/testrichtext.c \
../src/gtk+/tests/testscale.c \
../src/gtk+/tests/testscrolledge.c \
../src/gtk+/tests/testscrolledwindow.c \
../src/gtk+/tests/testselection.c \
../src/gtk+/tests/testselectionmode.c \
../src/gtk+/tests/testsensitive.c \
../src/gtk+/tests/testsocket.c \
../src/gtk+/tests/testsocket_child.c \
../src/gtk+/tests/testsocket_common.c \
../src/gtk+/tests/testspinbutton.c \
../src/gtk+/tests/testsplitheaders.c \
../src/gtk+/tests/teststack.c \
../src/gtk+/tests/teststatusicon.c \
../src/gtk+/tests/teststockbuttonmenu.c \
../src/gtk+/tests/testswitch.c \
../src/gtk+/tests/testtextview.c \
../src/gtk+/tests/testthreads.c \
../src/gtk+/tests/testtitlebar.c \
../src/gtk+/tests/testtoolbar.c \
../src/gtk+/tests/testtoolbar2.c \
../src/gtk+/tests/testtooltips.c \
../src/gtk+/tests/testtoplevelembed.c \
../src/gtk+/tests/testtreechanging.c \
../src/gtk+/tests/testtreecolumns.c \
../src/gtk+/tests/testtreecolumnsizing.c \
../src/gtk+/tests/testtreeedit.c \
../src/gtk+/tests/testtreeflow.c \
../src/gtk+/tests/testtreefocus.c \
../src/gtk+/tests/testtreemenu.c \
../src/gtk+/tests/testtreemodel.c \
../src/gtk+/tests/testtreepos.c \
../src/gtk+/tests/testtreesort.c \
../src/gtk+/tests/testtreeview.c \
../src/gtk+/tests/testverticalcells.c \
../src/gtk+/tests/testvolumebutton.c \
../src/gtk+/tests/testwindows.c \
../src/gtk+/tests/testwindowsize.c \
../src/gtk+/tests/testxinerama.c \
../src/gtk+/tests/treestoretest.c \
../src/gtk+/tests/variable.c \
../src/gtk+/tests/video-timer.c 

CC_SRCS += \
../src/gtk+/tests/autotestkeywords.cc 

OBJS += \
./src/gtk+/tests/animated-resizing.o \
./src/gtk+/tests/animated-revealing.o \
./src/gtk+/tests/autotestkeywords.o \
./src/gtk+/tests/flicker.o \
./src/gtk+/tests/frame-stats.o \
./src/gtk+/tests/gdkgears.o \
./src/gtk+/tests/gtkgears.o \
./src/gtk+/tests/gtkoffscreenbox.o \
./src/gtk+/tests/motion-compression.o \
./src/gtk+/tests/overlayscroll.o \
./src/gtk+/tests/print-editor.o \
./src/gtk+/tests/scrolling-performance.o \
./src/gtk+/tests/simple.o \
./src/gtk+/tests/stresstest-toolbar.o \
./src/gtk+/tests/styleexamples.o \
./src/gtk+/tests/subsurface.o \
./src/gtk+/tests/syncscroll.o \
./src/gtk+/tests/testaccel.o \
./src/gtk+/tests/testactionbar.o \
./src/gtk+/tests/testactions.o \
./src/gtk+/tests/testadjustsize.o \
./src/gtk+/tests/testanimation.o \
./src/gtk+/tests/testappchooser.o \
./src/gtk+/tests/testappchooserbutton.o \
./src/gtk+/tests/testassistant.o \
./src/gtk+/tests/testbaseline.o \
./src/gtk+/tests/testbbox.o \
./src/gtk+/tests/testbox.o \
./src/gtk+/tests/testboxcss.o \
./src/gtk+/tests/testbuttons.o \
./src/gtk+/tests/testcairo.o \
./src/gtk+/tests/testcalendar.o \
./src/gtk+/tests/testcellarea.o \
./src/gtk+/tests/testcellrenderertext.o \
./src/gtk+/tests/testclipboard.o \
./src/gtk+/tests/testcolorchooser.o \
./src/gtk+/tests/testcombo.o \
./src/gtk+/tests/testcombochange.o \
./src/gtk+/tests/testdialog.o \
./src/gtk+/tests/testdnd.o \
./src/gtk+/tests/testellipsise.o \
./src/gtk+/tests/testemblems.o \
./src/gtk+/tests/testentrycompletion.o \
./src/gtk+/tests/testentryicons.o \
./src/gtk+/tests/testerrors.o \
./src/gtk+/tests/testexpand.o \
./src/gtk+/tests/testexpander.o \
./src/gtk+/tests/testfilechooser.o \
./src/gtk+/tests/testfilechooserbutton.o \
./src/gtk+/tests/testflowbox.o \
./src/gtk+/tests/testfontchooser.o \
./src/gtk+/tests/testfontchooserdialog.o \
./src/gtk+/tests/testfontselection.o \
./src/gtk+/tests/testfontselectiondialog.o \
./src/gtk+/tests/testframe.o \
./src/gtk+/tests/testfullscreen.o \
./src/gtk+/tests/testgeometry.o \
./src/gtk+/tests/testgiconpixbuf.o \
./src/gtk+/tests/testglarea.o \
./src/gtk+/tests/testglblending.o \
./src/gtk+/tests/testgmenu.o \
./src/gtk+/tests/testgrid.o \
./src/gtk+/tests/testgrouping.o \
./src/gtk+/tests/testgtk.o \
./src/gtk+/tests/testheaderbar.o \
./src/gtk+/tests/testheightforwidth.o \
./src/gtk+/tests/testicontheme.o \
./src/gtk+/tests/testiconview-keynav.o \
./src/gtk+/tests/testiconview.o \
./src/gtk+/tests/testimage.o \
./src/gtk+/tests/testinput.o \
./src/gtk+/tests/testkineticscrolling.o \
./src/gtk+/tests/testlevelbar.o \
./src/gtk+/tests/testlist.o \
./src/gtk+/tests/testlist2.o \
./src/gtk+/tests/testlist3.o \
./src/gtk+/tests/testlockbutton.o \
./src/gtk+/tests/testlogout.o \
./src/gtk+/tests/testmenubutton.o \
./src/gtk+/tests/testmerge.o \
./src/gtk+/tests/testmountoperation.o \
./src/gtk+/tests/testmultidisplay.o \
./src/gtk+/tests/testnoscreen.o \
./src/gtk+/tests/testnotebookdnd.o \
./src/gtk+/tests/testnouiprint.o \
./src/gtk+/tests/testnumerableicon.o \
./src/gtk+/tests/testoffscreen.o \
./src/gtk+/tests/testoffscreenwindow.o \
./src/gtk+/tests/testorientable.o \
./src/gtk+/tests/testoverlay.o \
./src/gtk+/tests/testoverlaystyleclass.o \
./src/gtk+/tests/testpixbuf-color.o \
./src/gtk+/tests/testpixbuf-save.o \
./src/gtk+/tests/testpixbuf-scale.o \
./src/gtk+/tests/testpopover.o \
./src/gtk+/tests/testprint.o \
./src/gtk+/tests/testprintfileoperation.o \
./src/gtk+/tests/testrc.o \
./src/gtk+/tests/testrecentchooser.o \
./src/gtk+/tests/testrecentchoosermenu.o \
./src/gtk+/tests/testrevealer.o \
./src/gtk+/tests/testrichtext.o \
./src/gtk+/tests/testscale.o \
./src/gtk+/tests/testscrolledge.o \
./src/gtk+/tests/testscrolledwindow.o \
./src/gtk+/tests/testselection.o \
./src/gtk+/tests/testselectionmode.o \
./src/gtk+/tests/testsensitive.o \
./src/gtk+/tests/testsocket.o \
./src/gtk+/tests/testsocket_child.o \
./src/gtk+/tests/testsocket_common.o \
./src/gtk+/tests/testspinbutton.o \
./src/gtk+/tests/testsplitheaders.o \
./src/gtk+/tests/teststack.o \
./src/gtk+/tests/teststatusicon.o \
./src/gtk+/tests/teststockbuttonmenu.o \
./src/gtk+/tests/testswitch.o \
./src/gtk+/tests/testtextview.o \
./src/gtk+/tests/testthreads.o \
./src/gtk+/tests/testtitlebar.o \
./src/gtk+/tests/testtoolbar.o \
./src/gtk+/tests/testtoolbar2.o \
./src/gtk+/tests/testtooltips.o \
./src/gtk+/tests/testtoplevelembed.o \
./src/gtk+/tests/testtreechanging.o \
./src/gtk+/tests/testtreecolumns.o \
./src/gtk+/tests/testtreecolumnsizing.o \
./src/gtk+/tests/testtreeedit.o \
./src/gtk+/tests/testtreeflow.o \
./src/gtk+/tests/testtreefocus.o \
./src/gtk+/tests/testtreemenu.o \
./src/gtk+/tests/testtreemodel.o \
./src/gtk+/tests/testtreepos.o \
./src/gtk+/tests/testtreesort.o \
./src/gtk+/tests/testtreeview.o \
./src/gtk+/tests/testverticalcells.o \
./src/gtk+/tests/testvolumebutton.o \
./src/gtk+/tests/testwindows.o \
./src/gtk+/tests/testwindowsize.o \
./src/gtk+/tests/testxinerama.o \
./src/gtk+/tests/treestoretest.o \
./src/gtk+/tests/variable.o \
./src/gtk+/tests/video-timer.o 

C_DEPS += \
./src/gtk+/tests/animated-resizing.d \
./src/gtk+/tests/animated-revealing.d \
./src/gtk+/tests/flicker.d \
./src/gtk+/tests/frame-stats.d \
./src/gtk+/tests/gdkgears.d \
./src/gtk+/tests/gtkgears.d \
./src/gtk+/tests/gtkoffscreenbox.d \
./src/gtk+/tests/motion-compression.d \
./src/gtk+/tests/overlayscroll.d \
./src/gtk+/tests/print-editor.d \
./src/gtk+/tests/scrolling-performance.d \
./src/gtk+/tests/simple.d \
./src/gtk+/tests/stresstest-toolbar.d \
./src/gtk+/tests/styleexamples.d \
./src/gtk+/tests/subsurface.d \
./src/gtk+/tests/syncscroll.d \
./src/gtk+/tests/testaccel.d \
./src/gtk+/tests/testactionbar.d \
./src/gtk+/tests/testactions.d \
./src/gtk+/tests/testadjustsize.d \
./src/gtk+/tests/testanimation.d \
./src/gtk+/tests/testappchooser.d \
./src/gtk+/tests/testappchooserbutton.d \
./src/gtk+/tests/testassistant.d \
./src/gtk+/tests/testbaseline.d \
./src/gtk+/tests/testbbox.d \
./src/gtk+/tests/testbox.d \
./src/gtk+/tests/testboxcss.d \
./src/gtk+/tests/testbuttons.d \
./src/gtk+/tests/testcairo.d \
./src/gtk+/tests/testcalendar.d \
./src/gtk+/tests/testcellarea.d \
./src/gtk+/tests/testcellrenderertext.d \
./src/gtk+/tests/testclipboard.d \
./src/gtk+/tests/testcolorchooser.d \
./src/gtk+/tests/testcombo.d \
./src/gtk+/tests/testcombochange.d \
./src/gtk+/tests/testdialog.d \
./src/gtk+/tests/testdnd.d \
./src/gtk+/tests/testellipsise.d \
./src/gtk+/tests/testemblems.d \
./src/gtk+/tests/testentrycompletion.d \
./src/gtk+/tests/testentryicons.d \
./src/gtk+/tests/testerrors.d \
./src/gtk+/tests/testexpand.d \
./src/gtk+/tests/testexpander.d \
./src/gtk+/tests/testfilechooser.d \
./src/gtk+/tests/testfilechooserbutton.d \
./src/gtk+/tests/testflowbox.d \
./src/gtk+/tests/testfontchooser.d \
./src/gtk+/tests/testfontchooserdialog.d \
./src/gtk+/tests/testfontselection.d \
./src/gtk+/tests/testfontselectiondialog.d \
./src/gtk+/tests/testframe.d \
./src/gtk+/tests/testfullscreen.d \
./src/gtk+/tests/testgeometry.d \
./src/gtk+/tests/testgiconpixbuf.d \
./src/gtk+/tests/testglarea.d \
./src/gtk+/tests/testglblending.d \
./src/gtk+/tests/testgmenu.d \
./src/gtk+/tests/testgrid.d \
./src/gtk+/tests/testgrouping.d \
./src/gtk+/tests/testgtk.d \
./src/gtk+/tests/testheaderbar.d \
./src/gtk+/tests/testheightforwidth.d \
./src/gtk+/tests/testicontheme.d \
./src/gtk+/tests/testiconview-keynav.d \
./src/gtk+/tests/testiconview.d \
./src/gtk+/tests/testimage.d \
./src/gtk+/tests/testinput.d \
./src/gtk+/tests/testkineticscrolling.d \
./src/gtk+/tests/testlevelbar.d \
./src/gtk+/tests/testlist.d \
./src/gtk+/tests/testlist2.d \
./src/gtk+/tests/testlist3.d \
./src/gtk+/tests/testlockbutton.d \
./src/gtk+/tests/testlogout.d \
./src/gtk+/tests/testmenubutton.d \
./src/gtk+/tests/testmerge.d \
./src/gtk+/tests/testmountoperation.d \
./src/gtk+/tests/testmultidisplay.d \
./src/gtk+/tests/testnoscreen.d \
./src/gtk+/tests/testnotebookdnd.d \
./src/gtk+/tests/testnouiprint.d \
./src/gtk+/tests/testnumerableicon.d \
./src/gtk+/tests/testoffscreen.d \
./src/gtk+/tests/testoffscreenwindow.d \
./src/gtk+/tests/testorientable.d \
./src/gtk+/tests/testoverlay.d \
./src/gtk+/tests/testoverlaystyleclass.d \
./src/gtk+/tests/testpixbuf-color.d \
./src/gtk+/tests/testpixbuf-save.d \
./src/gtk+/tests/testpixbuf-scale.d \
./src/gtk+/tests/testpopover.d \
./src/gtk+/tests/testprint.d \
./src/gtk+/tests/testprintfileoperation.d \
./src/gtk+/tests/testrc.d \
./src/gtk+/tests/testrecentchooser.d \
./src/gtk+/tests/testrecentchoosermenu.d \
./src/gtk+/tests/testrevealer.d \
./src/gtk+/tests/testrichtext.d \
./src/gtk+/tests/testscale.d \
./src/gtk+/tests/testscrolledge.d \
./src/gtk+/tests/testscrolledwindow.d \
./src/gtk+/tests/testselection.d \
./src/gtk+/tests/testselectionmode.d \
./src/gtk+/tests/testsensitive.d \
./src/gtk+/tests/testsocket.d \
./src/gtk+/tests/testsocket_child.d \
./src/gtk+/tests/testsocket_common.d \
./src/gtk+/tests/testspinbutton.d \
./src/gtk+/tests/testsplitheaders.d \
./src/gtk+/tests/teststack.d \
./src/gtk+/tests/teststatusicon.d \
./src/gtk+/tests/teststockbuttonmenu.d \
./src/gtk+/tests/testswitch.d \
./src/gtk+/tests/testtextview.d \
./src/gtk+/tests/testthreads.d \
./src/gtk+/tests/testtitlebar.d \
./src/gtk+/tests/testtoolbar.d \
./src/gtk+/tests/testtoolbar2.d \
./src/gtk+/tests/testtooltips.d \
./src/gtk+/tests/testtoplevelembed.d \
./src/gtk+/tests/testtreechanging.d \
./src/gtk+/tests/testtreecolumns.d \
./src/gtk+/tests/testtreecolumnsizing.d \
./src/gtk+/tests/testtreeedit.d \
./src/gtk+/tests/testtreeflow.d \
./src/gtk+/tests/testtreefocus.d \
./src/gtk+/tests/testtreemenu.d \
./src/gtk+/tests/testtreemodel.d \
./src/gtk+/tests/testtreepos.d \
./src/gtk+/tests/testtreesort.d \
./src/gtk+/tests/testtreeview.d \
./src/gtk+/tests/testverticalcells.d \
./src/gtk+/tests/testvolumebutton.d \
./src/gtk+/tests/testwindows.d \
./src/gtk+/tests/testwindowsize.d \
./src/gtk+/tests/testxinerama.d \
./src/gtk+/tests/treestoretest.d \
./src/gtk+/tests/variable.d \
./src/gtk+/tests/video-timer.d 

CC_DEPS += \
./src/gtk+/tests/autotestkeywords.d 


# Each subdirectory must supply rules for building sources it contributes
src/gtk+/tests/%.o: ../src/gtk+/tests/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 `pkg-config --cflags glib-2.0` -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

src/gtk+/tests/%.o: ../src/gtk+/tests/%.cc
	@echo 'Building file: $<'
	@echo 'Invoking: Cross G++ Compiler'
	g++ -std=c++11 -I/usr/include/gtk-3.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/pixman-1 -I/usr/include/libpng12 -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


