################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/gtk+/gtk/encodesymbolic.c \
../src/gtk+/gtk/fallback-c89.c \
../src/gtk+/gtk/fnmatch.c \
../src/gtk+/gtk/gen-paper-names.c \
../src/gtk+/gtk/gtk-launch.c \
../src/gtk+/gtk/gtkaboutdialog.c \
../src/gtk+/gtk/gtkaccelgroup.c \
../src/gtk+/gtk/gtkaccellabel.c \
../src/gtk+/gtk/gtkaccelmap.c \
../src/gtk+/gtk/gtkaccessible.c \
../src/gtk+/gtk/gtkactionable.c \
../src/gtk+/gtk/gtkactionbar.c \
../src/gtk+/gtk/gtkactionhelper.c \
../src/gtk+/gtk/gtkactionmuxer.c \
../src/gtk+/gtk/gtkactionobservable.c \
../src/gtk+/gtk/gtkactionobserver.c \
../src/gtk+/gtk/gtkadjustment.c \
../src/gtk+/gtk/gtkallocatedbitmask.c \
../src/gtk+/gtk/gtkappchooser.c \
../src/gtk+/gtk/gtkappchooserbutton.c \
../src/gtk+/gtk/gtkappchooserdialog.c \
../src/gtk+/gtk/gtkappchooserwidget.c \
../src/gtk+/gtk/gtkapplication-dbus.c \
../src/gtk+/gtk/gtkapplication-quartz-menu.c \
../src/gtk+/gtk/gtkapplication-quartz.c \
../src/gtk+/gtk/gtkapplication-wayland.c \
../src/gtk+/gtk/gtkapplication-x11.c \
../src/gtk+/gtk/gtkapplication.c \
../src/gtk+/gtk/gtkapplicationimpl.c \
../src/gtk+/gtk/gtkapplicationwindow.c \
../src/gtk+/gtk/gtkaspectframe.c \
../src/gtk+/gtk/gtkassistant.c \
../src/gtk+/gtk/gtkbbox.c \
../src/gtk+/gtk/gtkbin.c \
../src/gtk+/gtk/gtkbindings.c \
../src/gtk+/gtk/gtkbookmarksmanager.c \
../src/gtk+/gtk/gtkborder.c \
../src/gtk+/gtk/gtkbox.c \
../src/gtk+/gtk/gtkbuildable.c \
../src/gtk+/gtk/gtkbuilder-menus.c \
../src/gtk+/gtk/gtkbuilder.c \
../src/gtk+/gtk/gtkbuilderparser.c \
../src/gtk+/gtk/gtkbutton.c \
../src/gtk+/gtk/gtkcairoblur.c \
../src/gtk+/gtk/gtkcalendar.c \
../src/gtk+/gtk/gtkcellarea.c \
../src/gtk+/gtk/gtkcellareabox.c \
../src/gtk+/gtk/gtkcellareaboxcontext.c \
../src/gtk+/gtk/gtkcellareacontext.c \
../src/gtk+/gtk/gtkcelleditable.c \
../src/gtk+/gtk/gtkcelllayout.c \
../src/gtk+/gtk/gtkcellrenderer.c \
../src/gtk+/gtk/gtkcellrendereraccel.c \
../src/gtk+/gtk/gtkcellrenderercombo.c \
../src/gtk+/gtk/gtkcellrendererpixbuf.c \
../src/gtk+/gtk/gtkcellrendererprogress.c \
../src/gtk+/gtk/gtkcellrendererspin.c \
../src/gtk+/gtk/gtkcellrendererspinner.c \
../src/gtk+/gtk/gtkcellrenderertext.c \
../src/gtk+/gtk/gtkcellrenderertoggle.c \
../src/gtk+/gtk/gtkcellview.c \
../src/gtk+/gtk/gtkcheckbutton.c \
../src/gtk+/gtk/gtkcheckmenuitem.c \
../src/gtk+/gtk/gtkclipboard-quartz.c \
../src/gtk+/gtk/gtkclipboard.c \
../src/gtk+/gtk/gtkcolorbutton.c \
../src/gtk+/gtk/gtkcolorchooser.c \
../src/gtk+/gtk/gtkcolorchooserdialog.c \
../src/gtk+/gtk/gtkcolorchooserwidget.c \
../src/gtk+/gtk/gtkcoloreditor.c \
../src/gtk+/gtk/gtkcolorplane.c \
../src/gtk+/gtk/gtkcolorscale.c \
../src/gtk+/gtk/gtkcolorswatch.c \
../src/gtk+/gtk/gtkcolorutils.c \
../src/gtk+/gtk/gtkcombobox.c \
../src/gtk+/gtk/gtkcomboboxtext.c \
../src/gtk+/gtk/gtkcontainer.c \
../src/gtk+/gtk/gtkcssanimatedstyle.c \
../src/gtk+/gtk/gtkcssanimation.c \
../src/gtk+/gtk/gtkcssarrayvalue.c \
../src/gtk+/gtk/gtkcssbgsizevalue.c \
../src/gtk+/gtk/gtkcssbordervalue.c \
../src/gtk+/gtk/gtkcsscolorvalue.c \
../src/gtk+/gtk/gtkcsscornervalue.c \
../src/gtk+/gtk/gtkcsscustomproperty.c \
../src/gtk+/gtk/gtkcsseasevalue.c \
../src/gtk+/gtk/gtkcssenginevalue.c \
../src/gtk+/gtk/gtkcssenumvalue.c \
../src/gtk+/gtk/gtkcssiconthemevalue.c \
../src/gtk+/gtk/gtkcssimage.c \
../src/gtk+/gtk/gtkcssimagebuiltin.c \
../src/gtk+/gtk/gtkcssimagecrossfade.c \
../src/gtk+/gtk/gtkcssimagegradient.c \
../src/gtk+/gtk/gtkcssimageicontheme.c \
../src/gtk+/gtk/gtkcssimagelinear.c \
../src/gtk+/gtk/gtkcssimagescaled.c \
../src/gtk+/gtk/gtkcssimagesurface.c \
../src/gtk+/gtk/gtkcssimageurl.c \
../src/gtk+/gtk/gtkcssimagevalue.c \
../src/gtk+/gtk/gtkcssimagewin32.c \
../src/gtk+/gtk/gtkcssinheritvalue.c \
../src/gtk+/gtk/gtkcssinitialvalue.c \
../src/gtk+/gtk/gtkcsskeyframes.c \
../src/gtk+/gtk/gtkcsslookup.c \
../src/gtk+/gtk/gtkcssmatcher.c \
../src/gtk+/gtk/gtkcssnodedeclaration.c \
../src/gtk+/gtk/gtkcssnumbervalue.c \
../src/gtk+/gtk/gtkcssparser.c \
../src/gtk+/gtk/gtkcsspositionvalue.c \
../src/gtk+/gtk/gtkcssprovider.c \
../src/gtk+/gtk/gtkcssrepeatvalue.c \
../src/gtk+/gtk/gtkcssrgbavalue.c \
../src/gtk+/gtk/gtkcsssection.c \
../src/gtk+/gtk/gtkcssselector.c \
../src/gtk+/gtk/gtkcssshadowsvalue.c \
../src/gtk+/gtk/gtkcssshadowvalue.c \
../src/gtk+/gtk/gtkcssshorthandproperty.c \
../src/gtk+/gtk/gtkcssshorthandpropertyimpl.c \
../src/gtk+/gtk/gtkcssstaticstyle.c \
../src/gtk+/gtk/gtkcssstringvalue.c \
../src/gtk+/gtk/gtkcssstyle.c \
../src/gtk+/gtk/gtkcssstylefuncs.c \
../src/gtk+/gtk/gtkcssstyleproperty.c \
../src/gtk+/gtk/gtkcssstylepropertyimpl.c \
../src/gtk+/gtk/gtkcsstransformvalue.c \
../src/gtk+/gtk/gtkcsstransition.c \
../src/gtk+/gtk/gtkcsstypedvalue.c \
../src/gtk+/gtk/gtkcsstypes.c \
../src/gtk+/gtk/gtkcssunsetvalue.c \
../src/gtk+/gtk/gtkcssvalue.c \
../src/gtk+/gtk/gtkcustompaperunixdialog.c \
../src/gtk+/gtk/gtkdialog.c \
../src/gtk+/gtk/gtkdnd-quartz.c \
../src/gtk+/gtk/gtkdnd.c \
../src/gtk+/gtk/gtkdrawingarea.c \
../src/gtk+/gtk/gtkeditable.c \
../src/gtk+/gtk/gtkentry.c \
../src/gtk+/gtk/gtkentrybuffer.c \
../src/gtk+/gtk/gtkentrycompletion.c \
../src/gtk+/gtk/gtkeventbox.c \
../src/gtk+/gtk/gtkeventcontroller.c \
../src/gtk+/gtk/gtkexpander.c \
../src/gtk+/gtk/gtkfilechooser.c \
../src/gtk+/gtk/gtkfilechooserbutton.c \
../src/gtk+/gtk/gtkfilechooserdialog.c \
../src/gtk+/gtk/gtkfilechooserembed.c \
../src/gtk+/gtk/gtkfilechooserentry.c \
../src/gtk+/gtk/gtkfilechooserutils.c \
../src/gtk+/gtk/gtkfilechooserwidget.c \
../src/gtk+/gtk/gtkfilefilter.c \
../src/gtk+/gtk/gtkfilesystem.c \
../src/gtk+/gtk/gtkfilesystemmodel.c \
../src/gtk+/gtk/gtkfixed.c \
../src/gtk+/gtk/gtkflowbox.c \
../src/gtk+/gtk/gtkfontbutton.c \
../src/gtk+/gtk/gtkfontchooser.c \
../src/gtk+/gtk/gtkfontchooserdialog.c \
../src/gtk+/gtk/gtkfontchooserutils.c \
../src/gtk+/gtk/gtkfontchooserwidget.c \
../src/gtk+/gtk/gtkframe.c \
../src/gtk+/gtk/gtkgesture.c \
../src/gtk+/gtk/gtkgesturedrag.c \
../src/gtk+/gtk/gtkgesturelongpress.c \
../src/gtk+/gtk/gtkgesturemultipress.c \
../src/gtk+/gtk/gtkgesturepan.c \
../src/gtk+/gtk/gtkgesturerotate.c \
../src/gtk+/gtk/gtkgesturesingle.c \
../src/gtk+/gtk/gtkgestureswipe.c \
../src/gtk+/gtk/gtkgesturezoom.c \
../src/gtk+/gtk/gtkgladecatalog.c \
../src/gtk+/gtk/gtkglarea.c \
../src/gtk+/gtk/gtkgrid.c \
../src/gtk+/gtk/gtkheaderbar.c \
../src/gtk+/gtk/gtkhsla.c \
../src/gtk+/gtk/gtkiconcache.c \
../src/gtk+/gtk/gtkiconcachevalidator.c \
../src/gtk+/gtk/gtkiconhelper.c \
../src/gtk+/gtk/gtkicontheme.c \
../src/gtk+/gtk/gtkiconview.c \
../src/gtk+/gtk/gtkimage.c \
../src/gtk+/gtk/gtkimcontext.c \
../src/gtk+/gtk/gtkimcontextsimple.c \
../src/gtk+/gtk/gtkimmodule.c \
../src/gtk+/gtk/gtkimmulticontext.c \
../src/gtk+/gtk/gtkinfobar.c \
../src/gtk+/gtk/gtkinvisible.c \
../src/gtk+/gtk/gtkkeyhash.c \
../src/gtk+/gtk/gtkkineticscrolling.c \
../src/gtk+/gtk/gtklabel.c \
../src/gtk+/gtk/gtklayout.c \
../src/gtk+/gtk/gtklevelbar.c \
../src/gtk+/gtk/gtklinkbutton.c \
../src/gtk+/gtk/gtklistbox.c \
../src/gtk+/gtk/gtkliststore.c \
../src/gtk+/gtk/gtklockbutton.c \
../src/gtk+/gtk/gtkmagnifier.c \
../src/gtk+/gtk/gtkmain.c \
../src/gtk+/gtk/gtkmenu.c \
../src/gtk+/gtk/gtkmenubar.c \
../src/gtk+/gtk/gtkmenubutton.c \
../src/gtk+/gtk/gtkmenuitem.c \
../src/gtk+/gtk/gtkmenusectionbox.c \
../src/gtk+/gtk/gtkmenushell.c \
../src/gtk+/gtk/gtkmenutoolbutton.c \
../src/gtk+/gtk/gtkmenutracker.c \
../src/gtk+/gtk/gtkmenutrackeritem.c \
../src/gtk+/gtk/gtkmessagedialog.c \
../src/gtk+/gtk/gtkmnemonichash.c \
../src/gtk+/gtk/gtkmodelbutton.c \
../src/gtk+/gtk/gtkmodelmenuitem.c \
../src/gtk+/gtk/gtkmodifierstyle.c \
../src/gtk+/gtk/gtkmodules.c \
../src/gtk+/gtk/gtkmountoperation-stub.c \
../src/gtk+/gtk/gtkmountoperation-x11.c \
../src/gtk+/gtk/gtkmountoperation.c \
../src/gtk+/gtk/gtknotebook.c \
../src/gtk+/gtk/gtkoffscreenwindow.c \
../src/gtk+/gtk/gtkorientable.c \
../src/gtk+/gtk/gtkoverlay.c \
../src/gtk+/gtk/gtkpagesetup.c \
../src/gtk+/gtk/gtkpagesetupunixdialog.c \
../src/gtk+/gtk/gtkpaned.c \
../src/gtk+/gtk/gtkpango.c \
../src/gtk+/gtk/gtkpapersize.c \
../src/gtk+/gtk/gtkpathbar.c \
../src/gtk+/gtk/gtkpixelcache.c \
../src/gtk+/gtk/gtkplacessidebar.c \
../src/gtk+/gtk/gtkplug.c \
../src/gtk+/gtk/gtkpopover.c \
../src/gtk+/gtk/gtkpopovermenu.c \
../src/gtk+/gtk/gtkprint-win32.c \
../src/gtk+/gtk/gtkprintbackend.c \
../src/gtk+/gtk/gtkprintcontext.c \
../src/gtk+/gtk/gtkprinter.c \
../src/gtk+/gtk/gtkprinteroption.c \
../src/gtk+/gtk/gtkprinteroptionset.c \
../src/gtk+/gtk/gtkprinteroptionwidget.c \
../src/gtk+/gtk/gtkprintjob.c \
../src/gtk+/gtk/gtkprintoperation-unix.c \
../src/gtk+/gtk/gtkprintoperation-win32.c \
../src/gtk+/gtk/gtkprintoperation.c \
../src/gtk+/gtk/gtkprintoperationpreview.c \
../src/gtk+/gtk/gtkprintsettings.c \
../src/gtk+/gtk/gtkprintunixdialog.c \
../src/gtk+/gtk/gtkprintutils.c \
../src/gtk+/gtk/gtkprivate.c \
../src/gtk+/gtk/gtkprogressbar.c \
../src/gtk+/gtk/gtkquartz.c \
../src/gtk+/gtk/gtkquery.c \
../src/gtk+/gtk/gtkradiobutton.c \
../src/gtk+/gtk/gtkradiomenuitem.c \
../src/gtk+/gtk/gtkradiotoolbutton.c \
../src/gtk+/gtk/gtkrange.c \
../src/gtk+/gtk/gtkrbtree.c \
../src/gtk+/gtk/gtkrecentchooser.c \
../src/gtk+/gtk/gtkrecentchooserdefault.c \
../src/gtk+/gtk/gtkrecentchooserdialog.c \
../src/gtk+/gtk/gtkrecentchoosermenu.c \
../src/gtk+/gtk/gtkrecentchooserutils.c \
../src/gtk+/gtk/gtkrecentchooserwidget.c \
../src/gtk+/gtk/gtkrecentfilter.c \
../src/gtk+/gtk/gtkrecentmanager.c \
../src/gtk+/gtk/gtkrender.c \
../src/gtk+/gtk/gtkrenderbackground.c \
../src/gtk+/gtk/gtkrenderborder.c \
../src/gtk+/gtk/gtkrendericon.c \
../src/gtk+/gtk/gtkrevealer.c \
../src/gtk+/gtk/gtkroundedbox.c \
../src/gtk+/gtk/gtkscale.c \
../src/gtk+/gtk/gtkscalebutton.c \
../src/gtk+/gtk/gtkscrollable.c \
../src/gtk+/gtk/gtkscrollbar.c \
../src/gtk+/gtk/gtkscrolledwindow.c \
../src/gtk+/gtk/gtksearchbar.c \
../src/gtk+/gtk/gtksearchengine.c \
../src/gtk+/gtk/gtksearchenginequartz.c \
../src/gtk+/gtk/gtksearchenginesimple.c \
../src/gtk+/gtk/gtksearchenginetracker.c \
../src/gtk+/gtk/gtksearchentry.c \
../src/gtk+/gtk/gtkselection.c \
../src/gtk+/gtk/gtkseparator.c \
../src/gtk+/gtk/gtkseparatormenuitem.c \
../src/gtk+/gtk/gtkseparatortoolitem.c \
../src/gtk+/gtk/gtksettings.c \
../src/gtk+/gtk/gtkshow.c \
../src/gtk+/gtk/gtksizegroup.c \
../src/gtk+/gtk/gtksizerequest.c \
../src/gtk+/gtk/gtksizerequestcache.c \
../src/gtk+/gtk/gtksocket.c \
../src/gtk+/gtk/gtkspinbutton.c \
../src/gtk+/gtk/gtkspinner.c \
../src/gtk+/gtk/gtkstack.c \
../src/gtk+/gtk/gtkstacksidebar.c \
../src/gtk+/gtk/gtkstackswitcher.c \
../src/gtk+/gtk/gtkstatusbar.c \
../src/gtk+/gtk/gtkstyleanimation.c \
../src/gtk+/gtk/gtkstylecascade.c \
../src/gtk+/gtk/gtkstylecontext.c \
../src/gtk+/gtk/gtkstyleproperty.c \
../src/gtk+/gtk/gtkstyleprovider.c \
../src/gtk+/gtk/gtkstyleproviderprivate.c \
../src/gtk+/gtk/gtkswitch.c \
../src/gtk+/gtk/gtktestutils.c \
../src/gtk+/gtk/gtktextattributes.c \
../src/gtk+/gtk/gtktextbtree.c \
../src/gtk+/gtk/gtktextbuffer.c \
../src/gtk+/gtk/gtktextbufferrichtext.c \
../src/gtk+/gtk/gtktextbufferserialize.c \
../src/gtk+/gtk/gtktextchild.c \
../src/gtk+/gtk/gtktextdisplay.c \
../src/gtk+/gtk/gtktexthandle.c \
../src/gtk+/gtk/gtktextiter.c \
../src/gtk+/gtk/gtktextlayout.c \
../src/gtk+/gtk/gtktextmark.c \
../src/gtk+/gtk/gtktextsegment.c \
../src/gtk+/gtk/gtktexttag.c \
../src/gtk+/gtk/gtktexttagtable.c \
../src/gtk+/gtk/gtktexttypes.c \
../src/gtk+/gtk/gtktextutil.c \
../src/gtk+/gtk/gtktextview.c \
../src/gtk+/gtk/gtktogglebutton.c \
../src/gtk+/gtk/gtktoggletoolbutton.c \
../src/gtk+/gtk/gtktoolbar.c \
../src/gtk+/gtk/gtktoolbutton.c \
../src/gtk+/gtk/gtktoolitem.c \
../src/gtk+/gtk/gtktoolitemgroup.c \
../src/gtk+/gtk/gtktoolpalette.c \
../src/gtk+/gtk/gtktoolshell.c \
../src/gtk+/gtk/gtktooltip.c \
../src/gtk+/gtk/gtktrashmonitor.c \
../src/gtk+/gtk/gtktreedatalist.c \
../src/gtk+/gtk/gtktreednd.c \
../src/gtk+/gtk/gtktreemenu.c \
../src/gtk+/gtk/gtktreemodel.c \
../src/gtk+/gtk/gtktreemodelfilter.c \
../src/gtk+/gtk/gtktreemodelsort.c \
../src/gtk+/gtk/gtktreeselection.c \
../src/gtk+/gtk/gtktreesortable.c \
../src/gtk+/gtk/gtktreestore.c \
../src/gtk+/gtk/gtktreeview.c \
../src/gtk+/gtk/gtktreeviewcolumn.c \
../src/gtk+/gtk/gtkviewport.c \
../src/gtk+/gtk/gtkvolumebutton.c \
../src/gtk+/gtk/gtkwidget.c \
../src/gtk+/gtk/gtkwidgetpath.c \
../src/gtk+/gtk/gtkwin32.c \
../src/gtk+/gtk/gtkwin32embed.c \
../src/gtk+/gtk/gtkwin32embedwidget.c \
../src/gtk+/gtk/gtkwin32theme.c \
../src/gtk+/gtk/gtkwindow.c \
../src/gtk+/gtk/gtkwindowgroup.c \
../src/gtk+/gtk/gtkxembed.c \
../src/gtk+/gtk/paper_names.c \
../src/gtk+/gtk/paper_names_offsets.c \
../src/gtk+/gtk/queryimmodules.c \
../src/gtk+/gtk/updateiconcache.c 

OBJS += \
./src/gtk+/gtk/encodesymbolic.o \
./src/gtk+/gtk/fallback-c89.o \
./src/gtk+/gtk/fnmatch.o \
./src/gtk+/gtk/gen-paper-names.o \
./src/gtk+/gtk/gtk-launch.o \
./src/gtk+/gtk/gtkaboutdialog.o \
./src/gtk+/gtk/gtkaccelgroup.o \
./src/gtk+/gtk/gtkaccellabel.o \
./src/gtk+/gtk/gtkaccelmap.o \
./src/gtk+/gtk/gtkaccessible.o \
./src/gtk+/gtk/gtkactionable.o \
./src/gtk+/gtk/gtkactionbar.o \
./src/gtk+/gtk/gtkactionhelper.o \
./src/gtk+/gtk/gtkactionmuxer.o \
./src/gtk+/gtk/gtkactionobservable.o \
./src/gtk+/gtk/gtkactionobserver.o \
./src/gtk+/gtk/gtkadjustment.o \
./src/gtk+/gtk/gtkallocatedbitmask.o \
./src/gtk+/gtk/gtkappchooser.o \
./src/gtk+/gtk/gtkappchooserbutton.o \
./src/gtk+/gtk/gtkappchooserdialog.o \
./src/gtk+/gtk/gtkappchooserwidget.o \
./src/gtk+/gtk/gtkapplication-dbus.o \
./src/gtk+/gtk/gtkapplication-quartz-menu.o \
./src/gtk+/gtk/gtkapplication-quartz.o \
./src/gtk+/gtk/gtkapplication-wayland.o \
./src/gtk+/gtk/gtkapplication-x11.o \
./src/gtk+/gtk/gtkapplication.o \
./src/gtk+/gtk/gtkapplicationimpl.o \
./src/gtk+/gtk/gtkapplicationwindow.o \
./src/gtk+/gtk/gtkaspectframe.o \
./src/gtk+/gtk/gtkassistant.o \
./src/gtk+/gtk/gtkbbox.o \
./src/gtk+/gtk/gtkbin.o \
./src/gtk+/gtk/gtkbindings.o \
./src/gtk+/gtk/gtkbookmarksmanager.o \
./src/gtk+/gtk/gtkborder.o \
./src/gtk+/gtk/gtkbox.o \
./src/gtk+/gtk/gtkbuildable.o \
./src/gtk+/gtk/gtkbuilder-menus.o \
./src/gtk+/gtk/gtkbuilder.o \
./src/gtk+/gtk/gtkbuilderparser.o \
./src/gtk+/gtk/gtkbutton.o \
./src/gtk+/gtk/gtkcairoblur.o \
./src/gtk+/gtk/gtkcalendar.o \
./src/gtk+/gtk/gtkcellarea.o \
./src/gtk+/gtk/gtkcellareabox.o \
./src/gtk+/gtk/gtkcellareaboxcontext.o \
./src/gtk+/gtk/gtkcellareacontext.o \
./src/gtk+/gtk/gtkcelleditable.o \
./src/gtk+/gtk/gtkcelllayout.o \
./src/gtk+/gtk/gtkcellrenderer.o \
./src/gtk+/gtk/gtkcellrendereraccel.o \
./src/gtk+/gtk/gtkcellrenderercombo.o \
./src/gtk+/gtk/gtkcellrendererpixbuf.o \
./src/gtk+/gtk/gtkcellrendererprogress.o \
./src/gtk+/gtk/gtkcellrendererspin.o \
./src/gtk+/gtk/gtkcellrendererspinner.o \
./src/gtk+/gtk/gtkcellrenderertext.o \
./src/gtk+/gtk/gtkcellrenderertoggle.o \
./src/gtk+/gtk/gtkcellview.o \
./src/gtk+/gtk/gtkcheckbutton.o \
./src/gtk+/gtk/gtkcheckmenuitem.o \
./src/gtk+/gtk/gtkclipboard-quartz.o \
./src/gtk+/gtk/gtkclipboard.o \
./src/gtk+/gtk/gtkcolorbutton.o \
./src/gtk+/gtk/gtkcolorchooser.o \
./src/gtk+/gtk/gtkcolorchooserdialog.o \
./src/gtk+/gtk/gtkcolorchooserwidget.o \
./src/gtk+/gtk/gtkcoloreditor.o \
./src/gtk+/gtk/gtkcolorplane.o \
./src/gtk+/gtk/gtkcolorscale.o \
./src/gtk+/gtk/gtkcolorswatch.o \
./src/gtk+/gtk/gtkcolorutils.o \
./src/gtk+/gtk/gtkcombobox.o \
./src/gtk+/gtk/gtkcomboboxtext.o \
./src/gtk+/gtk/gtkcontainer.o \
./src/gtk+/gtk/gtkcssanimatedstyle.o \
./src/gtk+/gtk/gtkcssanimation.o \
./src/gtk+/gtk/gtkcssarrayvalue.o \
./src/gtk+/gtk/gtkcssbgsizevalue.o \
./src/gtk+/gtk/gtkcssbordervalue.o \
./src/gtk+/gtk/gtkcsscolorvalue.o \
./src/gtk+/gtk/gtkcsscornervalue.o \
./src/gtk+/gtk/gtkcsscustomproperty.o \
./src/gtk+/gtk/gtkcsseasevalue.o \
./src/gtk+/gtk/gtkcssenginevalue.o \
./src/gtk+/gtk/gtkcssenumvalue.o \
./src/gtk+/gtk/gtkcssiconthemevalue.o \
./src/gtk+/gtk/gtkcssimage.o \
./src/gtk+/gtk/gtkcssimagebuiltin.o \
./src/gtk+/gtk/gtkcssimagecrossfade.o \
./src/gtk+/gtk/gtkcssimagegradient.o \
./src/gtk+/gtk/gtkcssimageicontheme.o \
./src/gtk+/gtk/gtkcssimagelinear.o \
./src/gtk+/gtk/gtkcssimagescaled.o \
./src/gtk+/gtk/gtkcssimagesurface.o \
./src/gtk+/gtk/gtkcssimageurl.o \
./src/gtk+/gtk/gtkcssimagevalue.o \
./src/gtk+/gtk/gtkcssimagewin32.o \
./src/gtk+/gtk/gtkcssinheritvalue.o \
./src/gtk+/gtk/gtkcssinitialvalue.o \
./src/gtk+/gtk/gtkcsskeyframes.o \
./src/gtk+/gtk/gtkcsslookup.o \
./src/gtk+/gtk/gtkcssmatcher.o \
./src/gtk+/gtk/gtkcssnodedeclaration.o \
./src/gtk+/gtk/gtkcssnumbervalue.o \
./src/gtk+/gtk/gtkcssparser.o \
./src/gtk+/gtk/gtkcsspositionvalue.o \
./src/gtk+/gtk/gtkcssprovider.o \
./src/gtk+/gtk/gtkcssrepeatvalue.o \
./src/gtk+/gtk/gtkcssrgbavalue.o \
./src/gtk+/gtk/gtkcsssection.o \
./src/gtk+/gtk/gtkcssselector.o \
./src/gtk+/gtk/gtkcssshadowsvalue.o \
./src/gtk+/gtk/gtkcssshadowvalue.o \
./src/gtk+/gtk/gtkcssshorthandproperty.o \
./src/gtk+/gtk/gtkcssshorthandpropertyimpl.o \
./src/gtk+/gtk/gtkcssstaticstyle.o \
./src/gtk+/gtk/gtkcssstringvalue.o \
./src/gtk+/gtk/gtkcssstyle.o \
./src/gtk+/gtk/gtkcssstylefuncs.o \
./src/gtk+/gtk/gtkcssstyleproperty.o \
./src/gtk+/gtk/gtkcssstylepropertyimpl.o \
./src/gtk+/gtk/gtkcsstransformvalue.o \
./src/gtk+/gtk/gtkcsstransition.o \
./src/gtk+/gtk/gtkcsstypedvalue.o \
./src/gtk+/gtk/gtkcsstypes.o \
./src/gtk+/gtk/gtkcssunsetvalue.o \
./src/gtk+/gtk/gtkcssvalue.o \
./src/gtk+/gtk/gtkcustompaperunixdialog.o \
./src/gtk+/gtk/gtkdialog.o \
./src/gtk+/gtk/gtkdnd-quartz.o \
./src/gtk+/gtk/gtkdnd.o \
./src/gtk+/gtk/gtkdrawingarea.o \
./src/gtk+/gtk/gtkeditable.o \
./src/gtk+/gtk/gtkentry.o \
./src/gtk+/gtk/gtkentrybuffer.o \
./src/gtk+/gtk/gtkentrycompletion.o \
./src/gtk+/gtk/gtkeventbox.o \
./src/gtk+/gtk/gtkeventcontroller.o \
./src/gtk+/gtk/gtkexpander.o \
./src/gtk+/gtk/gtkfilechooser.o \
./src/gtk+/gtk/gtkfilechooserbutton.o \
./src/gtk+/gtk/gtkfilechooserdialog.o \
./src/gtk+/gtk/gtkfilechooserembed.o \
./src/gtk+/gtk/gtkfilechooserentry.o \
./src/gtk+/gtk/gtkfilechooserutils.o \
./src/gtk+/gtk/gtkfilechooserwidget.o \
./src/gtk+/gtk/gtkfilefilter.o \
./src/gtk+/gtk/gtkfilesystem.o \
./src/gtk+/gtk/gtkfilesystemmodel.o \
./src/gtk+/gtk/gtkfixed.o \
./src/gtk+/gtk/gtkflowbox.o \
./src/gtk+/gtk/gtkfontbutton.o \
./src/gtk+/gtk/gtkfontchooser.o \
./src/gtk+/gtk/gtkfontchooserdialog.o \
./src/gtk+/gtk/gtkfontchooserutils.o \
./src/gtk+/gtk/gtkfontchooserwidget.o \
./src/gtk+/gtk/gtkframe.o \
./src/gtk+/gtk/gtkgesture.o \
./src/gtk+/gtk/gtkgesturedrag.o \
./src/gtk+/gtk/gtkgesturelongpress.o \
./src/gtk+/gtk/gtkgesturemultipress.o \
./src/gtk+/gtk/gtkgesturepan.o \
./src/gtk+/gtk/gtkgesturerotate.o \
./src/gtk+/gtk/gtkgesturesingle.o \
./src/gtk+/gtk/gtkgestureswipe.o \
./src/gtk+/gtk/gtkgesturezoom.o \
./src/gtk+/gtk/gtkgladecatalog.o \
./src/gtk+/gtk/gtkglarea.o \
./src/gtk+/gtk/gtkgrid.o \
./src/gtk+/gtk/gtkheaderbar.o \
./src/gtk+/gtk/gtkhsla.o \
./src/gtk+/gtk/gtkiconcache.o \
./src/gtk+/gtk/gtkiconcachevalidator.o \
./src/gtk+/gtk/gtkiconhelper.o \
./src/gtk+/gtk/gtkicontheme.o \
./src/gtk+/gtk/gtkiconview.o \
./src/gtk+/gtk/gtkimage.o \
./src/gtk+/gtk/gtkimcontext.o \
./src/gtk+/gtk/gtkimcontextsimple.o \
./src/gtk+/gtk/gtkimmodule.o \
./src/gtk+/gtk/gtkimmulticontext.o \
./src/gtk+/gtk/gtkinfobar.o \
./src/gtk+/gtk/gtkinvisible.o \
./src/gtk+/gtk/gtkkeyhash.o \
./src/gtk+/gtk/gtkkineticscrolling.o \
./src/gtk+/gtk/gtklabel.o \
./src/gtk+/gtk/gtklayout.o \
./src/gtk+/gtk/gtklevelbar.o \
./src/gtk+/gtk/gtklinkbutton.o \
./src/gtk+/gtk/gtklistbox.o \
./src/gtk+/gtk/gtkliststore.o \
./src/gtk+/gtk/gtklockbutton.o \
./src/gtk+/gtk/gtkmagnifier.o \
./src/gtk+/gtk/gtkmain.o \
./src/gtk+/gtk/gtkmenu.o \
./src/gtk+/gtk/gtkmenubar.o \
./src/gtk+/gtk/gtkmenubutton.o \
./src/gtk+/gtk/gtkmenuitem.o \
./src/gtk+/gtk/gtkmenusectionbox.o \
./src/gtk+/gtk/gtkmenushell.o \
./src/gtk+/gtk/gtkmenutoolbutton.o \
./src/gtk+/gtk/gtkmenutracker.o \
./src/gtk+/gtk/gtkmenutrackeritem.o \
./src/gtk+/gtk/gtkmessagedialog.o \
./src/gtk+/gtk/gtkmnemonichash.o \
./src/gtk+/gtk/gtkmodelbutton.o \
./src/gtk+/gtk/gtkmodelmenuitem.o \
./src/gtk+/gtk/gtkmodifierstyle.o \
./src/gtk+/gtk/gtkmodules.o \
./src/gtk+/gtk/gtkmountoperation-stub.o \
./src/gtk+/gtk/gtkmountoperation-x11.o \
./src/gtk+/gtk/gtkmountoperation.o \
./src/gtk+/gtk/gtknotebook.o \
./src/gtk+/gtk/gtkoffscreenwindow.o \
./src/gtk+/gtk/gtkorientable.o \
./src/gtk+/gtk/gtkoverlay.o \
./src/gtk+/gtk/gtkpagesetup.o \
./src/gtk+/gtk/gtkpagesetupunixdialog.o \
./src/gtk+/gtk/gtkpaned.o \
./src/gtk+/gtk/gtkpango.o \
./src/gtk+/gtk/gtkpapersize.o \
./src/gtk+/gtk/gtkpathbar.o \
./src/gtk+/gtk/gtkpixelcache.o \
./src/gtk+/gtk/gtkplacessidebar.o \
./src/gtk+/gtk/gtkplug.o \
./src/gtk+/gtk/gtkpopover.o \
./src/gtk+/gtk/gtkpopovermenu.o \
./src/gtk+/gtk/gtkprint-win32.o \
./src/gtk+/gtk/gtkprintbackend.o \
./src/gtk+/gtk/gtkprintcontext.o \
./src/gtk+/gtk/gtkprinter.o \
./src/gtk+/gtk/gtkprinteroption.o \
./src/gtk+/gtk/gtkprinteroptionset.o \
./src/gtk+/gtk/gtkprinteroptionwidget.o \
./src/gtk+/gtk/gtkprintjob.o \
./src/gtk+/gtk/gtkprintoperation-unix.o \
./src/gtk+/gtk/gtkprintoperation-win32.o \
./src/gtk+/gtk/gtkprintoperation.o \
./src/gtk+/gtk/gtkprintoperationpreview.o \
./src/gtk+/gtk/gtkprintsettings.o \
./src/gtk+/gtk/gtkprintunixdialog.o \
./src/gtk+/gtk/gtkprintutils.o \
./src/gtk+/gtk/gtkprivate.o \
./src/gtk+/gtk/gtkprogressbar.o \
./src/gtk+/gtk/gtkquartz.o \
./src/gtk+/gtk/gtkquery.o \
./src/gtk+/gtk/gtkradiobutton.o \
./src/gtk+/gtk/gtkradiomenuitem.o \
./src/gtk+/gtk/gtkradiotoolbutton.o \
./src/gtk+/gtk/gtkrange.o \
./src/gtk+/gtk/gtkrbtree.o \
./src/gtk+/gtk/gtkrecentchooser.o \
./src/gtk+/gtk/gtkrecentchooserdefault.o \
./src/gtk+/gtk/gtkrecentchooserdialog.o \
./src/gtk+/gtk/gtkrecentchoosermenu.o \
./src/gtk+/gtk/gtkrecentchooserutils.o \
./src/gtk+/gtk/gtkrecentchooserwidget.o \
./src/gtk+/gtk/gtkrecentfilter.o \
./src/gtk+/gtk/gtkrecentmanager.o \
./src/gtk+/gtk/gtkrender.o \
./src/gtk+/gtk/gtkrenderbackground.o \
./src/gtk+/gtk/gtkrenderborder.o \
./src/gtk+/gtk/gtkrendericon.o \
./src/gtk+/gtk/gtkrevealer.o \
./src/gtk+/gtk/gtkroundedbox.o \
./src/gtk+/gtk/gtkscale.o \
./src/gtk+/gtk/gtkscalebutton.o \
./src/gtk+/gtk/gtkscrollable.o \
./src/gtk+/gtk/gtkscrollbar.o \
./src/gtk+/gtk/gtkscrolledwindow.o \
./src/gtk+/gtk/gtksearchbar.o \
./src/gtk+/gtk/gtksearchengine.o \
./src/gtk+/gtk/gtksearchenginequartz.o \
./src/gtk+/gtk/gtksearchenginesimple.o \
./src/gtk+/gtk/gtksearchenginetracker.o \
./src/gtk+/gtk/gtksearchentry.o \
./src/gtk+/gtk/gtkselection.o \
./src/gtk+/gtk/gtkseparator.o \
./src/gtk+/gtk/gtkseparatormenuitem.o \
./src/gtk+/gtk/gtkseparatortoolitem.o \
./src/gtk+/gtk/gtksettings.o \
./src/gtk+/gtk/gtkshow.o \
./src/gtk+/gtk/gtksizegroup.o \
./src/gtk+/gtk/gtksizerequest.o \
./src/gtk+/gtk/gtksizerequestcache.o \
./src/gtk+/gtk/gtksocket.o \
./src/gtk+/gtk/gtkspinbutton.o \
./src/gtk+/gtk/gtkspinner.o \
./src/gtk+/gtk/gtkstack.o \
./src/gtk+/gtk/gtkstacksidebar.o \
./src/gtk+/gtk/gtkstackswitcher.o \
./src/gtk+/gtk/gtkstatusbar.o \
./src/gtk+/gtk/gtkstyleanimation.o \
./src/gtk+/gtk/gtkstylecascade.o \
./src/gtk+/gtk/gtkstylecontext.o \
./src/gtk+/gtk/gtkstyleproperty.o \
./src/gtk+/gtk/gtkstyleprovider.o \
./src/gtk+/gtk/gtkstyleproviderprivate.o \
./src/gtk+/gtk/gtkswitch.o \
./src/gtk+/gtk/gtktestutils.o \
./src/gtk+/gtk/gtktextattributes.o \
./src/gtk+/gtk/gtktextbtree.o \
./src/gtk+/gtk/gtktextbuffer.o \
./src/gtk+/gtk/gtktextbufferrichtext.o \
./src/gtk+/gtk/gtktextbufferserialize.o \
./src/gtk+/gtk/gtktextchild.o \
./src/gtk+/gtk/gtktextdisplay.o \
./src/gtk+/gtk/gtktexthandle.o \
./src/gtk+/gtk/gtktextiter.o \
./src/gtk+/gtk/gtktextlayout.o \
./src/gtk+/gtk/gtktextmark.o \
./src/gtk+/gtk/gtktextsegment.o \
./src/gtk+/gtk/gtktexttag.o \
./src/gtk+/gtk/gtktexttagtable.o \
./src/gtk+/gtk/gtktexttypes.o \
./src/gtk+/gtk/gtktextutil.o \
./src/gtk+/gtk/gtktextview.o \
./src/gtk+/gtk/gtktogglebutton.o \
./src/gtk+/gtk/gtktoggletoolbutton.o \
./src/gtk+/gtk/gtktoolbar.o \
./src/gtk+/gtk/gtktoolbutton.o \
./src/gtk+/gtk/gtktoolitem.o \
./src/gtk+/gtk/gtktoolitemgroup.o \
./src/gtk+/gtk/gtktoolpalette.o \
./src/gtk+/gtk/gtktoolshell.o \
./src/gtk+/gtk/gtktooltip.o \
./src/gtk+/gtk/gtktrashmonitor.o \
./src/gtk+/gtk/gtktreedatalist.o \
./src/gtk+/gtk/gtktreednd.o \
./src/gtk+/gtk/gtktreemenu.o \
./src/gtk+/gtk/gtktreemodel.o \
./src/gtk+/gtk/gtktreemodelfilter.o \
./src/gtk+/gtk/gtktreemodelsort.o \
./src/gtk+/gtk/gtktreeselection.o \
./src/gtk+/gtk/gtktreesortable.o \
./src/gtk+/gtk/gtktreestore.o \
./src/gtk+/gtk/gtktreeview.o \
./src/gtk+/gtk/gtktreeviewcolumn.o \
./src/gtk+/gtk/gtkviewport.o \
./src/gtk+/gtk/gtkvolumebutton.o \
./src/gtk+/gtk/gtkwidget.o \
./src/gtk+/gtk/gtkwidgetpath.o \
./src/gtk+/gtk/gtkwin32.o \
./src/gtk+/gtk/gtkwin32embed.o \
./src/gtk+/gtk/gtkwin32embedwidget.o \
./src/gtk+/gtk/gtkwin32theme.o \
./src/gtk+/gtk/gtkwindow.o \
./src/gtk+/gtk/gtkwindowgroup.o \
./src/gtk+/gtk/gtkxembed.o \
./src/gtk+/gtk/paper_names.o \
./src/gtk+/gtk/paper_names_offsets.o \
./src/gtk+/gtk/queryimmodules.o \
./src/gtk+/gtk/updateiconcache.o 

C_DEPS += \
./src/gtk+/gtk/encodesymbolic.d \
./src/gtk+/gtk/fallback-c89.d \
./src/gtk+/gtk/fnmatch.d \
./src/gtk+/gtk/gen-paper-names.d \
./src/gtk+/gtk/gtk-launch.d \
./src/gtk+/gtk/gtkaboutdialog.d \
./src/gtk+/gtk/gtkaccelgroup.d \
./src/gtk+/gtk/gtkaccellabel.d \
./src/gtk+/gtk/gtkaccelmap.d \
./src/gtk+/gtk/gtkaccessible.d \
./src/gtk+/gtk/gtkactionable.d \
./src/gtk+/gtk/gtkactionbar.d \
./src/gtk+/gtk/gtkactionhelper.d \
./src/gtk+/gtk/gtkactionmuxer.d \
./src/gtk+/gtk/gtkactionobservable.d \
./src/gtk+/gtk/gtkactionobserver.d \
./src/gtk+/gtk/gtkadjustment.d \
./src/gtk+/gtk/gtkallocatedbitmask.d \
./src/gtk+/gtk/gtkappchooser.d \
./src/gtk+/gtk/gtkappchooserbutton.d \
./src/gtk+/gtk/gtkappchooserdialog.d \
./src/gtk+/gtk/gtkappchooserwidget.d \
./src/gtk+/gtk/gtkapplication-dbus.d \
./src/gtk+/gtk/gtkapplication-quartz-menu.d \
./src/gtk+/gtk/gtkapplication-quartz.d \
./src/gtk+/gtk/gtkapplication-wayland.d \
./src/gtk+/gtk/gtkapplication-x11.d \
./src/gtk+/gtk/gtkapplication.d \
./src/gtk+/gtk/gtkapplicationimpl.d \
./src/gtk+/gtk/gtkapplicationwindow.d \
./src/gtk+/gtk/gtkaspectframe.d \
./src/gtk+/gtk/gtkassistant.d \
./src/gtk+/gtk/gtkbbox.d \
./src/gtk+/gtk/gtkbin.d \
./src/gtk+/gtk/gtkbindings.d \
./src/gtk+/gtk/gtkbookmarksmanager.d \
./src/gtk+/gtk/gtkborder.d \
./src/gtk+/gtk/gtkbox.d \
./src/gtk+/gtk/gtkbuildable.d \
./src/gtk+/gtk/gtkbuilder-menus.d \
./src/gtk+/gtk/gtkbuilder.d \
./src/gtk+/gtk/gtkbuilderparser.d \
./src/gtk+/gtk/gtkbutton.d \
./src/gtk+/gtk/gtkcairoblur.d \
./src/gtk+/gtk/gtkcalendar.d \
./src/gtk+/gtk/gtkcellarea.d \
./src/gtk+/gtk/gtkcellareabox.d \
./src/gtk+/gtk/gtkcellareaboxcontext.d \
./src/gtk+/gtk/gtkcellareacontext.d \
./src/gtk+/gtk/gtkcelleditable.d \
./src/gtk+/gtk/gtkcelllayout.d \
./src/gtk+/gtk/gtkcellrenderer.d \
./src/gtk+/gtk/gtkcellrendereraccel.d \
./src/gtk+/gtk/gtkcellrenderercombo.d \
./src/gtk+/gtk/gtkcellrendererpixbuf.d \
./src/gtk+/gtk/gtkcellrendererprogress.d \
./src/gtk+/gtk/gtkcellrendererspin.d \
./src/gtk+/gtk/gtkcellrendererspinner.d \
./src/gtk+/gtk/gtkcellrenderertext.d \
./src/gtk+/gtk/gtkcellrenderertoggle.d \
./src/gtk+/gtk/gtkcellview.d \
./src/gtk+/gtk/gtkcheckbutton.d \
./src/gtk+/gtk/gtkcheckmenuitem.d \
./src/gtk+/gtk/gtkclipboard-quartz.d \
./src/gtk+/gtk/gtkclipboard.d \
./src/gtk+/gtk/gtkcolorbutton.d \
./src/gtk+/gtk/gtkcolorchooser.d \
./src/gtk+/gtk/gtkcolorchooserdialog.d \
./src/gtk+/gtk/gtkcolorchooserwidget.d \
./src/gtk+/gtk/gtkcoloreditor.d \
./src/gtk+/gtk/gtkcolorplane.d \
./src/gtk+/gtk/gtkcolorscale.d \
./src/gtk+/gtk/gtkcolorswatch.d \
./src/gtk+/gtk/gtkcolorutils.d \
./src/gtk+/gtk/gtkcombobox.d \
./src/gtk+/gtk/gtkcomboboxtext.d \
./src/gtk+/gtk/gtkcontainer.d \
./src/gtk+/gtk/gtkcssanimatedstyle.d \
./src/gtk+/gtk/gtkcssanimation.d \
./src/gtk+/gtk/gtkcssarrayvalue.d \
./src/gtk+/gtk/gtkcssbgsizevalue.d \
./src/gtk+/gtk/gtkcssbordervalue.d \
./src/gtk+/gtk/gtkcsscolorvalue.d \
./src/gtk+/gtk/gtkcsscornervalue.d \
./src/gtk+/gtk/gtkcsscustomproperty.d \
./src/gtk+/gtk/gtkcsseasevalue.d \
./src/gtk+/gtk/gtkcssenginevalue.d \
./src/gtk+/gtk/gtkcssenumvalue.d \
./src/gtk+/gtk/gtkcssiconthemevalue.d \
./src/gtk+/gtk/gtkcssimage.d \
./src/gtk+/gtk/gtkcssimagebuiltin.d \
./src/gtk+/gtk/gtkcssimagecrossfade.d \
./src/gtk+/gtk/gtkcssimagegradient.d \
./src/gtk+/gtk/gtkcssimageicontheme.d \
./src/gtk+/gtk/gtkcssimagelinear.d \
./src/gtk+/gtk/gtkcssimagescaled.d \
./src/gtk+/gtk/gtkcssimagesurface.d \
./src/gtk+/gtk/gtkcssimageurl.d \
./src/gtk+/gtk/gtkcssimagevalue.d \
./src/gtk+/gtk/gtkcssimagewin32.d \
./src/gtk+/gtk/gtkcssinheritvalue.d \
./src/gtk+/gtk/gtkcssinitialvalue.d \
./src/gtk+/gtk/gtkcsskeyframes.d \
./src/gtk+/gtk/gtkcsslookup.d \
./src/gtk+/gtk/gtkcssmatcher.d \
./src/gtk+/gtk/gtkcssnodedeclaration.d \
./src/gtk+/gtk/gtkcssnumbervalue.d \
./src/gtk+/gtk/gtkcssparser.d \
./src/gtk+/gtk/gtkcsspositionvalue.d \
./src/gtk+/gtk/gtkcssprovider.d \
./src/gtk+/gtk/gtkcssrepeatvalue.d \
./src/gtk+/gtk/gtkcssrgbavalue.d \
./src/gtk+/gtk/gtkcsssection.d \
./src/gtk+/gtk/gtkcssselector.d \
./src/gtk+/gtk/gtkcssshadowsvalue.d \
./src/gtk+/gtk/gtkcssshadowvalue.d \
./src/gtk+/gtk/gtkcssshorthandproperty.d \
./src/gtk+/gtk/gtkcssshorthandpropertyimpl.d \
./src/gtk+/gtk/gtkcssstaticstyle.d \
./src/gtk+/gtk/gtkcssstringvalue.d \
./src/gtk+/gtk/gtkcssstyle.d \
./src/gtk+/gtk/gtkcssstylefuncs.d \
./src/gtk+/gtk/gtkcssstyleproperty.d \
./src/gtk+/gtk/gtkcssstylepropertyimpl.d \
./src/gtk+/gtk/gtkcsstransformvalue.d \
./src/gtk+/gtk/gtkcsstransition.d \
./src/gtk+/gtk/gtkcsstypedvalue.d \
./src/gtk+/gtk/gtkcsstypes.d \
./src/gtk+/gtk/gtkcssunsetvalue.d \
./src/gtk+/gtk/gtkcssvalue.d \
./src/gtk+/gtk/gtkcustompaperunixdialog.d \
./src/gtk+/gtk/gtkdialog.d \
./src/gtk+/gtk/gtkdnd-quartz.d \
./src/gtk+/gtk/gtkdnd.d \
./src/gtk+/gtk/gtkdrawingarea.d \
./src/gtk+/gtk/gtkeditable.d \
./src/gtk+/gtk/gtkentry.d \
./src/gtk+/gtk/gtkentrybuffer.d \
./src/gtk+/gtk/gtkentrycompletion.d \
./src/gtk+/gtk/gtkeventbox.d \
./src/gtk+/gtk/gtkeventcontroller.d \
./src/gtk+/gtk/gtkexpander.d \
./src/gtk+/gtk/gtkfilechooser.d \
./src/gtk+/gtk/gtkfilechooserbutton.d \
./src/gtk+/gtk/gtkfilechooserdialog.d \
./src/gtk+/gtk/gtkfilechooserembed.d \
./src/gtk+/gtk/gtkfilechooserentry.d \
./src/gtk+/gtk/gtkfilechooserutils.d \
./src/gtk+/gtk/gtkfilechooserwidget.d \
./src/gtk+/gtk/gtkfilefilter.d \
./src/gtk+/gtk/gtkfilesystem.d \
./src/gtk+/gtk/gtkfilesystemmodel.d \
./src/gtk+/gtk/gtkfixed.d \
./src/gtk+/gtk/gtkflowbox.d \
./src/gtk+/gtk/gtkfontbutton.d \
./src/gtk+/gtk/gtkfontchooser.d \
./src/gtk+/gtk/gtkfontchooserdialog.d \
./src/gtk+/gtk/gtkfontchooserutils.d \
./src/gtk+/gtk/gtkfontchooserwidget.d \
./src/gtk+/gtk/gtkframe.d \
./src/gtk+/gtk/gtkgesture.d \
./src/gtk+/gtk/gtkgesturedrag.d \
./src/gtk+/gtk/gtkgesturelongpress.d \
./src/gtk+/gtk/gtkgesturemultipress.d \
./src/gtk+/gtk/gtkgesturepan.d \
./src/gtk+/gtk/gtkgesturerotate.d \
./src/gtk+/gtk/gtkgesturesingle.d \
./src/gtk+/gtk/gtkgestureswipe.d \
./src/gtk+/gtk/gtkgesturezoom.d \
./src/gtk+/gtk/gtkgladecatalog.d \
./src/gtk+/gtk/gtkglarea.d \
./src/gtk+/gtk/gtkgrid.d \
./src/gtk+/gtk/gtkheaderbar.d \
./src/gtk+/gtk/gtkhsla.d \
./src/gtk+/gtk/gtkiconcache.d \
./src/gtk+/gtk/gtkiconcachevalidator.d \
./src/gtk+/gtk/gtkiconhelper.d \
./src/gtk+/gtk/gtkicontheme.d \
./src/gtk+/gtk/gtkiconview.d \
./src/gtk+/gtk/gtkimage.d \
./src/gtk+/gtk/gtkimcontext.d \
./src/gtk+/gtk/gtkimcontextsimple.d \
./src/gtk+/gtk/gtkimmodule.d \
./src/gtk+/gtk/gtkimmulticontext.d \
./src/gtk+/gtk/gtkinfobar.d \
./src/gtk+/gtk/gtkinvisible.d \
./src/gtk+/gtk/gtkkeyhash.d \
./src/gtk+/gtk/gtkkineticscrolling.d \
./src/gtk+/gtk/gtklabel.d \
./src/gtk+/gtk/gtklayout.d \
./src/gtk+/gtk/gtklevelbar.d \
./src/gtk+/gtk/gtklinkbutton.d \
./src/gtk+/gtk/gtklistbox.d \
./src/gtk+/gtk/gtkliststore.d \
./src/gtk+/gtk/gtklockbutton.d \
./src/gtk+/gtk/gtkmagnifier.d \
./src/gtk+/gtk/gtkmain.d \
./src/gtk+/gtk/gtkmenu.d \
./src/gtk+/gtk/gtkmenubar.d \
./src/gtk+/gtk/gtkmenubutton.d \
./src/gtk+/gtk/gtkmenuitem.d \
./src/gtk+/gtk/gtkmenusectionbox.d \
./src/gtk+/gtk/gtkmenushell.d \
./src/gtk+/gtk/gtkmenutoolbutton.d \
./src/gtk+/gtk/gtkmenutracker.d \
./src/gtk+/gtk/gtkmenutrackeritem.d \
./src/gtk+/gtk/gtkmessagedialog.d \
./src/gtk+/gtk/gtkmnemonichash.d \
./src/gtk+/gtk/gtkmodelbutton.d \
./src/gtk+/gtk/gtkmodelmenuitem.d \
./src/gtk+/gtk/gtkmodifierstyle.d \
./src/gtk+/gtk/gtkmodules.d \
./src/gtk+/gtk/gtkmountoperation-stub.d \
./src/gtk+/gtk/gtkmountoperation-x11.d \
./src/gtk+/gtk/gtkmountoperation.d \
./src/gtk+/gtk/gtknotebook.d \
./src/gtk+/gtk/gtkoffscreenwindow.d \
./src/gtk+/gtk/gtkorientable.d \
./src/gtk+/gtk/gtkoverlay.d \
./src/gtk+/gtk/gtkpagesetup.d \
./src/gtk+/gtk/gtkpagesetupunixdialog.d \
./src/gtk+/gtk/gtkpaned.d \
./src/gtk+/gtk/gtkpango.d \
./src/gtk+/gtk/gtkpapersize.d \
./src/gtk+/gtk/gtkpathbar.d \
./src/gtk+/gtk/gtkpixelcache.d \
./src/gtk+/gtk/gtkplacessidebar.d \
./src/gtk+/gtk/gtkplug.d \
./src/gtk+/gtk/gtkpopover.d \
./src/gtk+/gtk/gtkpopovermenu.d \
./src/gtk+/gtk/gtkprint-win32.d \
./src/gtk+/gtk/gtkprintbackend.d \
./src/gtk+/gtk/gtkprintcontext.d \
./src/gtk+/gtk/gtkprinter.d \
./src/gtk+/gtk/gtkprinteroption.d \
./src/gtk+/gtk/gtkprinteroptionset.d \
./src/gtk+/gtk/gtkprinteroptionwidget.d \
./src/gtk+/gtk/gtkprintjob.d \
./src/gtk+/gtk/gtkprintoperation-unix.d \
./src/gtk+/gtk/gtkprintoperation-win32.d \
./src/gtk+/gtk/gtkprintoperation.d \
./src/gtk+/gtk/gtkprintoperationpreview.d \
./src/gtk+/gtk/gtkprintsettings.d \
./src/gtk+/gtk/gtkprintunixdialog.d \
./src/gtk+/gtk/gtkprintutils.d \
./src/gtk+/gtk/gtkprivate.d \
./src/gtk+/gtk/gtkprogressbar.d \
./src/gtk+/gtk/gtkquartz.d \
./src/gtk+/gtk/gtkquery.d \
./src/gtk+/gtk/gtkradiobutton.d \
./src/gtk+/gtk/gtkradiomenuitem.d \
./src/gtk+/gtk/gtkradiotoolbutton.d \
./src/gtk+/gtk/gtkrange.d \
./src/gtk+/gtk/gtkrbtree.d \
./src/gtk+/gtk/gtkrecentchooser.d \
./src/gtk+/gtk/gtkrecentchooserdefault.d \
./src/gtk+/gtk/gtkrecentchooserdialog.d \
./src/gtk+/gtk/gtkrecentchoosermenu.d \
./src/gtk+/gtk/gtkrecentchooserutils.d \
./src/gtk+/gtk/gtkrecentchooserwidget.d \
./src/gtk+/gtk/gtkrecentfilter.d \
./src/gtk+/gtk/gtkrecentmanager.d \
./src/gtk+/gtk/gtkrender.d \
./src/gtk+/gtk/gtkrenderbackground.d \
./src/gtk+/gtk/gtkrenderborder.d \
./src/gtk+/gtk/gtkrendericon.d \
./src/gtk+/gtk/gtkrevealer.d \
./src/gtk+/gtk/gtkroundedbox.d \
./src/gtk+/gtk/gtkscale.d \
./src/gtk+/gtk/gtkscalebutton.d \
./src/gtk+/gtk/gtkscrollable.d \
./src/gtk+/gtk/gtkscrollbar.d \
./src/gtk+/gtk/gtkscrolledwindow.d \
./src/gtk+/gtk/gtksearchbar.d \
./src/gtk+/gtk/gtksearchengine.d \
./src/gtk+/gtk/gtksearchenginequartz.d \
./src/gtk+/gtk/gtksearchenginesimple.d \
./src/gtk+/gtk/gtksearchenginetracker.d \
./src/gtk+/gtk/gtksearchentry.d \
./src/gtk+/gtk/gtkselection.d \
./src/gtk+/gtk/gtkseparator.d \
./src/gtk+/gtk/gtkseparatormenuitem.d \
./src/gtk+/gtk/gtkseparatortoolitem.d \
./src/gtk+/gtk/gtksettings.d \
./src/gtk+/gtk/gtkshow.d \
./src/gtk+/gtk/gtksizegroup.d \
./src/gtk+/gtk/gtksizerequest.d \
./src/gtk+/gtk/gtksizerequestcache.d \
./src/gtk+/gtk/gtksocket.d \
./src/gtk+/gtk/gtkspinbutton.d \
./src/gtk+/gtk/gtkspinner.d \
./src/gtk+/gtk/gtkstack.d \
./src/gtk+/gtk/gtkstacksidebar.d \
./src/gtk+/gtk/gtkstackswitcher.d \
./src/gtk+/gtk/gtkstatusbar.d \
./src/gtk+/gtk/gtkstyleanimation.d \
./src/gtk+/gtk/gtkstylecascade.d \
./src/gtk+/gtk/gtkstylecontext.d \
./src/gtk+/gtk/gtkstyleproperty.d \
./src/gtk+/gtk/gtkstyleprovider.d \
./src/gtk+/gtk/gtkstyleproviderprivate.d \
./src/gtk+/gtk/gtkswitch.d \
./src/gtk+/gtk/gtktestutils.d \
./src/gtk+/gtk/gtktextattributes.d \
./src/gtk+/gtk/gtktextbtree.d \
./src/gtk+/gtk/gtktextbuffer.d \
./src/gtk+/gtk/gtktextbufferrichtext.d \
./src/gtk+/gtk/gtktextbufferserialize.d \
./src/gtk+/gtk/gtktextchild.d \
./src/gtk+/gtk/gtktextdisplay.d \
./src/gtk+/gtk/gtktexthandle.d \
./src/gtk+/gtk/gtktextiter.d \
./src/gtk+/gtk/gtktextlayout.d \
./src/gtk+/gtk/gtktextmark.d \
./src/gtk+/gtk/gtktextsegment.d \
./src/gtk+/gtk/gtktexttag.d \
./src/gtk+/gtk/gtktexttagtable.d \
./src/gtk+/gtk/gtktexttypes.d \
./src/gtk+/gtk/gtktextutil.d \
./src/gtk+/gtk/gtktextview.d \
./src/gtk+/gtk/gtktogglebutton.d \
./src/gtk+/gtk/gtktoggletoolbutton.d \
./src/gtk+/gtk/gtktoolbar.d \
./src/gtk+/gtk/gtktoolbutton.d \
./src/gtk+/gtk/gtktoolitem.d \
./src/gtk+/gtk/gtktoolitemgroup.d \
./src/gtk+/gtk/gtktoolpalette.d \
./src/gtk+/gtk/gtktoolshell.d \
./src/gtk+/gtk/gtktooltip.d \
./src/gtk+/gtk/gtktrashmonitor.d \
./src/gtk+/gtk/gtktreedatalist.d \
./src/gtk+/gtk/gtktreednd.d \
./src/gtk+/gtk/gtktreemenu.d \
./src/gtk+/gtk/gtktreemodel.d \
./src/gtk+/gtk/gtktreemodelfilter.d \
./src/gtk+/gtk/gtktreemodelsort.d \
./src/gtk+/gtk/gtktreeselection.d \
./src/gtk+/gtk/gtktreesortable.d \
./src/gtk+/gtk/gtktreestore.d \
./src/gtk+/gtk/gtktreeview.d \
./src/gtk+/gtk/gtktreeviewcolumn.d \
./src/gtk+/gtk/gtkviewport.d \
./src/gtk+/gtk/gtkvolumebutton.d \
./src/gtk+/gtk/gtkwidget.d \
./src/gtk+/gtk/gtkwidgetpath.d \
./src/gtk+/gtk/gtkwin32.d \
./src/gtk+/gtk/gtkwin32embed.d \
./src/gtk+/gtk/gtkwin32embedwidget.d \
./src/gtk+/gtk/gtkwin32theme.d \
./src/gtk+/gtk/gtkwindow.d \
./src/gtk+/gtk/gtkwindowgroup.d \
./src/gtk+/gtk/gtkxembed.d \
./src/gtk+/gtk/paper_names.d \
./src/gtk+/gtk/paper_names_offsets.d \
./src/gtk+/gtk/queryimmodules.d \
./src/gtk+/gtk/updateiconcache.d 


# Each subdirectory must supply rules for building sources it contributes
src/gtk+/gtk/%.o: ../src/gtk+/gtk/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 `pkg-config --cflags glib-2.0 gtk+-3.0` -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


