################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../src/osg/src/osgPlugins/ive/AlphaFunc.cpp \
../src/osg/src/osgPlugins/ive/AnimationPath.cpp \
../src/osg/src/osgPlugins/ive/AnimationPathCallback.cpp \
../src/osg/src/osgPlugins/ive/AnisotropicLighting.cpp \
../src/osg/src/osgPlugins/ive/AutoTransform.cpp \
../src/osg/src/osgPlugins/ive/AzimElevationSector.cpp \
../src/osg/src/osgPlugins/ive/AzimSector.cpp \
../src/osg/src/osgPlugins/ive/Billboard.cpp \
../src/osg/src/osgPlugins/ive/BlendColor.cpp \
../src/osg/src/osgPlugins/ive/BlendEquation.cpp \
../src/osg/src/osgPlugins/ive/BlendFunc.cpp \
../src/osg/src/osgPlugins/ive/BlinkSequence.cpp \
../src/osg/src/osgPlugins/ive/BumpMapping.cpp \
../src/osg/src/osgPlugins/ive/Camera.cpp \
../src/osg/src/osgPlugins/ive/CameraView.cpp \
../src/osg/src/osgPlugins/ive/Cartoon.cpp \
../src/osg/src/osgPlugins/ive/ClipNode.cpp \
../src/osg/src/osgPlugins/ive/ClipPlane.cpp \
../src/osg/src/osgPlugins/ive/ClusterCullingCallback.cpp \
../src/osg/src/osgPlugins/ive/ColorMask.cpp \
../src/osg/src/osgPlugins/ive/CompositeLayer.cpp \
../src/osg/src/osgPlugins/ive/ConeSector.cpp \
../src/osg/src/osgPlugins/ive/ConvexPlanarOccluder.cpp \
../src/osg/src/osgPlugins/ive/ConvexPlanarPolygon.cpp \
../src/osg/src/osgPlugins/ive/CoordinateSystemNode.cpp \
../src/osg/src/osgPlugins/ive/CullFace.cpp \
../src/osg/src/osgPlugins/ive/DOFTransform.cpp \
../src/osg/src/osgPlugins/ive/DataInputStream.cpp \
../src/osg/src/osgPlugins/ive/DataOutputStream.cpp \
../src/osg/src/osgPlugins/ive/Depth.cpp \
../src/osg/src/osgPlugins/ive/DirectionalSector.cpp \
../src/osg/src/osgPlugins/ive/DrawArrayLengths.cpp \
../src/osg/src/osgPlugins/ive/DrawArrays.cpp \
../src/osg/src/osgPlugins/ive/DrawElementsUByte.cpp \
../src/osg/src/osgPlugins/ive/DrawElementsUInt.cpp \
../src/osg/src/osgPlugins/ive/DrawElementsUShort.cpp \
../src/osg/src/osgPlugins/ive/Drawable.cpp \
../src/osg/src/osgPlugins/ive/Effect.cpp \
../src/osg/src/osgPlugins/ive/ElevationSector.cpp \
../src/osg/src/osgPlugins/ive/EllipsoidModel.cpp \
../src/osg/src/osgPlugins/ive/Exception.cpp \
../src/osg/src/osgPlugins/ive/FadeText.cpp \
../src/osg/src/osgPlugins/ive/Fog.cpp \
../src/osg/src/osgPlugins/ive/FragmentProgram.cpp \
../src/osg/src/osgPlugins/ive/FrontFace.cpp \
../src/osg/src/osgPlugins/ive/Geode.cpp \
../src/osg/src/osgPlugins/ive/Geometry.cpp \
../src/osg/src/osgPlugins/ive/Group.cpp \
../src/osg/src/osgPlugins/ive/HeightFieldLayer.cpp \
../src/osg/src/osgPlugins/ive/Image.cpp \
../src/osg/src/osgPlugins/ive/ImageLayer.cpp \
../src/osg/src/osgPlugins/ive/ImageSequence.cpp \
../src/osg/src/osgPlugins/ive/Impostor.cpp \
../src/osg/src/osgPlugins/ive/LOD.cpp \
../src/osg/src/osgPlugins/ive/Layer.cpp \
../src/osg/src/osgPlugins/ive/Light.cpp \
../src/osg/src/osgPlugins/ive/LightModel.cpp \
../src/osg/src/osgPlugins/ive/LightPoint.cpp \
../src/osg/src/osgPlugins/ive/LightPointNode.cpp \
../src/osg/src/osgPlugins/ive/LightSource.cpp \
../src/osg/src/osgPlugins/ive/LineStipple.cpp \
../src/osg/src/osgPlugins/ive/LineWidth.cpp \
../src/osg/src/osgPlugins/ive/Locator.cpp \
../src/osg/src/osgPlugins/ive/Material.cpp \
../src/osg/src/osgPlugins/ive/MatrixTransform.cpp \
../src/osg/src/osgPlugins/ive/MultiSwitch.cpp \
../src/osg/src/osgPlugins/ive/MultiTextureControl.cpp \
../src/osg/src/osgPlugins/ive/Multisample.cpp \
../src/osg/src/osgPlugins/ive/Node.cpp \
../src/osg/src/osgPlugins/ive/Object.cpp \
../src/osg/src/osgPlugins/ive/OccluderNode.cpp \
../src/osg/src/osgPlugins/ive/OcclusionQueryNode.cpp \
../src/osg/src/osgPlugins/ive/PagedLOD.cpp \
../src/osg/src/osgPlugins/ive/Point.cpp \
../src/osg/src/osgPlugins/ive/PointSprite.cpp \
../src/osg/src/osgPlugins/ive/PolygonMode.cpp \
../src/osg/src/osgPlugins/ive/PolygonOffset.cpp \
../src/osg/src/osgPlugins/ive/PolygonStipple.cpp \
../src/osg/src/osgPlugins/ive/PositionAttitudeTransform.cpp \
../src/osg/src/osgPlugins/ive/PrimitiveSet.cpp \
../src/osg/src/osgPlugins/ive/Program.cpp \
../src/osg/src/osgPlugins/ive/ProxyNode.cpp \
../src/osg/src/osgPlugins/ive/ReaderWriterIVE.cpp \
../src/osg/src/osgPlugins/ive/Scissor.cpp \
../src/osg/src/osgPlugins/ive/Scribe.cpp \
../src/osg/src/osgPlugins/ive/Sequence.cpp \
../src/osg/src/osgPlugins/ive/ShadeModel.cpp \
../src/osg/src/osgPlugins/ive/Shader.cpp \
../src/osg/src/osgPlugins/ive/Shape.cpp \
../src/osg/src/osgPlugins/ive/ShapeAttributeList.cpp \
../src/osg/src/osgPlugins/ive/ShapeDrawable.cpp \
../src/osg/src/osgPlugins/ive/SpecularHighlights.cpp \
../src/osg/src/osgPlugins/ive/StateSet.cpp \
../src/osg/src/osgPlugins/ive/Stencil.cpp \
../src/osg/src/osgPlugins/ive/StencilTwoSided.cpp \
../src/osg/src/osgPlugins/ive/Switch.cpp \
../src/osg/src/osgPlugins/ive/SwitchLayer.cpp \
../src/osg/src/osgPlugins/ive/Terrain.cpp \
../src/osg/src/osgPlugins/ive/TerrainTile.cpp \
../src/osg/src/osgPlugins/ive/TexEnv.cpp \
../src/osg/src/osgPlugins/ive/TexEnvCombine.cpp \
../src/osg/src/osgPlugins/ive/TexGen.cpp \
../src/osg/src/osgPlugins/ive/TexGenNode.cpp \
../src/osg/src/osgPlugins/ive/TexMat.cpp \
../src/osg/src/osgPlugins/ive/Text.cpp \
../src/osg/src/osgPlugins/ive/Text3D.cpp \
../src/osg/src/osgPlugins/ive/Texture.cpp \
../src/osg/src/osgPlugins/ive/Texture1D.cpp \
../src/osg/src/osgPlugins/ive/Texture2D.cpp \
../src/osg/src/osgPlugins/ive/Texture2DArray.cpp \
../src/osg/src/osgPlugins/ive/Texture3D.cpp \
../src/osg/src/osgPlugins/ive/TextureCubeMap.cpp \
../src/osg/src/osgPlugins/ive/TextureRectangle.cpp \
../src/osg/src/osgPlugins/ive/Transform.cpp \
../src/osg/src/osgPlugins/ive/Uniform.cpp \
../src/osg/src/osgPlugins/ive/VertexProgram.cpp \
../src/osg/src/osgPlugins/ive/Viewport.cpp \
../src/osg/src/osgPlugins/ive/VisibilityGroup.cpp \
../src/osg/src/osgPlugins/ive/Volume.cpp \
../src/osg/src/osgPlugins/ive/VolumeCompositeLayer.cpp \
../src/osg/src/osgPlugins/ive/VolumeCompositeProperty.cpp \
../src/osg/src/osgPlugins/ive/VolumeImageLayer.cpp \
../src/osg/src/osgPlugins/ive/VolumeLayer.cpp \
../src/osg/src/osgPlugins/ive/VolumeLocator.cpp \
../src/osg/src/osgPlugins/ive/VolumePropertyAdjustmentCallback.cpp \
../src/osg/src/osgPlugins/ive/VolumeScalarProperty.cpp \
../src/osg/src/osgPlugins/ive/VolumeSwitchProperty.cpp \
../src/osg/src/osgPlugins/ive/VolumeTile.cpp \
../src/osg/src/osgPlugins/ive/VolumeTransferFunctionProperty.cpp 

OBJS += \
./src/osg/src/osgPlugins/ive/AlphaFunc.o \
./src/osg/src/osgPlugins/ive/AnimationPath.o \
./src/osg/src/osgPlugins/ive/AnimationPathCallback.o \
./src/osg/src/osgPlugins/ive/AnisotropicLighting.o \
./src/osg/src/osgPlugins/ive/AutoTransform.o \
./src/osg/src/osgPlugins/ive/AzimElevationSector.o \
./src/osg/src/osgPlugins/ive/AzimSector.o \
./src/osg/src/osgPlugins/ive/Billboard.o \
./src/osg/src/osgPlugins/ive/BlendColor.o \
./src/osg/src/osgPlugins/ive/BlendEquation.o \
./src/osg/src/osgPlugins/ive/BlendFunc.o \
./src/osg/src/osgPlugins/ive/BlinkSequence.o \
./src/osg/src/osgPlugins/ive/BumpMapping.o \
./src/osg/src/osgPlugins/ive/Camera.o \
./src/osg/src/osgPlugins/ive/CameraView.o \
./src/osg/src/osgPlugins/ive/Cartoon.o \
./src/osg/src/osgPlugins/ive/ClipNode.o \
./src/osg/src/osgPlugins/ive/ClipPlane.o \
./src/osg/src/osgPlugins/ive/ClusterCullingCallback.o \
./src/osg/src/osgPlugins/ive/ColorMask.o \
./src/osg/src/osgPlugins/ive/CompositeLayer.o \
./src/osg/src/osgPlugins/ive/ConeSector.o \
./src/osg/src/osgPlugins/ive/ConvexPlanarOccluder.o \
./src/osg/src/osgPlugins/ive/ConvexPlanarPolygon.o \
./src/osg/src/osgPlugins/ive/CoordinateSystemNode.o \
./src/osg/src/osgPlugins/ive/CullFace.o \
./src/osg/src/osgPlugins/ive/DOFTransform.o \
./src/osg/src/osgPlugins/ive/DataInputStream.o \
./src/osg/src/osgPlugins/ive/DataOutputStream.o \
./src/osg/src/osgPlugins/ive/Depth.o \
./src/osg/src/osgPlugins/ive/DirectionalSector.o \
./src/osg/src/osgPlugins/ive/DrawArrayLengths.o \
./src/osg/src/osgPlugins/ive/DrawArrays.o \
./src/osg/src/osgPlugins/ive/DrawElementsUByte.o \
./src/osg/src/osgPlugins/ive/DrawElementsUInt.o \
./src/osg/src/osgPlugins/ive/DrawElementsUShort.o \
./src/osg/src/osgPlugins/ive/Drawable.o \
./src/osg/src/osgPlugins/ive/Effect.o \
./src/osg/src/osgPlugins/ive/ElevationSector.o \
./src/osg/src/osgPlugins/ive/EllipsoidModel.o \
./src/osg/src/osgPlugins/ive/Exception.o \
./src/osg/src/osgPlugins/ive/FadeText.o \
./src/osg/src/osgPlugins/ive/Fog.o \
./src/osg/src/osgPlugins/ive/FragmentProgram.o \
./src/osg/src/osgPlugins/ive/FrontFace.o \
./src/osg/src/osgPlugins/ive/Geode.o \
./src/osg/src/osgPlugins/ive/Geometry.o \
./src/osg/src/osgPlugins/ive/Group.o \
./src/osg/src/osgPlugins/ive/HeightFieldLayer.o \
./src/osg/src/osgPlugins/ive/Image.o \
./src/osg/src/osgPlugins/ive/ImageLayer.o \
./src/osg/src/osgPlugins/ive/ImageSequence.o \
./src/osg/src/osgPlugins/ive/Impostor.o \
./src/osg/src/osgPlugins/ive/LOD.o \
./src/osg/src/osgPlugins/ive/Layer.o \
./src/osg/src/osgPlugins/ive/Light.o \
./src/osg/src/osgPlugins/ive/LightModel.o \
./src/osg/src/osgPlugins/ive/LightPoint.o \
./src/osg/src/osgPlugins/ive/LightPointNode.o \
./src/osg/src/osgPlugins/ive/LightSource.o \
./src/osg/src/osgPlugins/ive/LineStipple.o \
./src/osg/src/osgPlugins/ive/LineWidth.o \
./src/osg/src/osgPlugins/ive/Locator.o \
./src/osg/src/osgPlugins/ive/Material.o \
./src/osg/src/osgPlugins/ive/MatrixTransform.o \
./src/osg/src/osgPlugins/ive/MultiSwitch.o \
./src/osg/src/osgPlugins/ive/MultiTextureControl.o \
./src/osg/src/osgPlugins/ive/Multisample.o \
./src/osg/src/osgPlugins/ive/Node.o \
./src/osg/src/osgPlugins/ive/Object.o \
./src/osg/src/osgPlugins/ive/OccluderNode.o \
./src/osg/src/osgPlugins/ive/OcclusionQueryNode.o \
./src/osg/src/osgPlugins/ive/PagedLOD.o \
./src/osg/src/osgPlugins/ive/Point.o \
./src/osg/src/osgPlugins/ive/PointSprite.o \
./src/osg/src/osgPlugins/ive/PolygonMode.o \
./src/osg/src/osgPlugins/ive/PolygonOffset.o \
./src/osg/src/osgPlugins/ive/PolygonStipple.o \
./src/osg/src/osgPlugins/ive/PositionAttitudeTransform.o \
./src/osg/src/osgPlugins/ive/PrimitiveSet.o \
./src/osg/src/osgPlugins/ive/Program.o \
./src/osg/src/osgPlugins/ive/ProxyNode.o \
./src/osg/src/osgPlugins/ive/ReaderWriterIVE.o \
./src/osg/src/osgPlugins/ive/Scissor.o \
./src/osg/src/osgPlugins/ive/Scribe.o \
./src/osg/src/osgPlugins/ive/Sequence.o \
./src/osg/src/osgPlugins/ive/ShadeModel.o \
./src/osg/src/osgPlugins/ive/Shader.o \
./src/osg/src/osgPlugins/ive/Shape.o \
./src/osg/src/osgPlugins/ive/ShapeAttributeList.o \
./src/osg/src/osgPlugins/ive/ShapeDrawable.o \
./src/osg/src/osgPlugins/ive/SpecularHighlights.o \
./src/osg/src/osgPlugins/ive/StateSet.o \
./src/osg/src/osgPlugins/ive/Stencil.o \
./src/osg/src/osgPlugins/ive/StencilTwoSided.o \
./src/osg/src/osgPlugins/ive/Switch.o \
./src/osg/src/osgPlugins/ive/SwitchLayer.o \
./src/osg/src/osgPlugins/ive/Terrain.o \
./src/osg/src/osgPlugins/ive/TerrainTile.o \
./src/osg/src/osgPlugins/ive/TexEnv.o \
./src/osg/src/osgPlugins/ive/TexEnvCombine.o \
./src/osg/src/osgPlugins/ive/TexGen.o \
./src/osg/src/osgPlugins/ive/TexGenNode.o \
./src/osg/src/osgPlugins/ive/TexMat.o \
./src/osg/src/osgPlugins/ive/Text.o \
./src/osg/src/osgPlugins/ive/Text3D.o \
./src/osg/src/osgPlugins/ive/Texture.o \
./src/osg/src/osgPlugins/ive/Texture1D.o \
./src/osg/src/osgPlugins/ive/Texture2D.o \
./src/osg/src/osgPlugins/ive/Texture2DArray.o \
./src/osg/src/osgPlugins/ive/Texture3D.o \
./src/osg/src/osgPlugins/ive/TextureCubeMap.o \
./src/osg/src/osgPlugins/ive/TextureRectangle.o \
./src/osg/src/osgPlugins/ive/Transform.o \
./src/osg/src/osgPlugins/ive/Uniform.o \
./src/osg/src/osgPlugins/ive/VertexProgram.o \
./src/osg/src/osgPlugins/ive/Viewport.o \
./src/osg/src/osgPlugins/ive/VisibilityGroup.o \
./src/osg/src/osgPlugins/ive/Volume.o \
./src/osg/src/osgPlugins/ive/VolumeCompositeLayer.o \
./src/osg/src/osgPlugins/ive/VolumeCompositeProperty.o \
./src/osg/src/osgPlugins/ive/VolumeImageLayer.o \
./src/osg/src/osgPlugins/ive/VolumeLayer.o \
./src/osg/src/osgPlugins/ive/VolumeLocator.o \
./src/osg/src/osgPlugins/ive/VolumePropertyAdjustmentCallback.o \
./src/osg/src/osgPlugins/ive/VolumeScalarProperty.o \
./src/osg/src/osgPlugins/ive/VolumeSwitchProperty.o \
./src/osg/src/osgPlugins/ive/VolumeTile.o \
./src/osg/src/osgPlugins/ive/VolumeTransferFunctionProperty.o 

CPP_DEPS += \
./src/osg/src/osgPlugins/ive/AlphaFunc.d \
./src/osg/src/osgPlugins/ive/AnimationPath.d \
./src/osg/src/osgPlugins/ive/AnimationPathCallback.d \
./src/osg/src/osgPlugins/ive/AnisotropicLighting.d \
./src/osg/src/osgPlugins/ive/AutoTransform.d \
./src/osg/src/osgPlugins/ive/AzimElevationSector.d \
./src/osg/src/osgPlugins/ive/AzimSector.d \
./src/osg/src/osgPlugins/ive/Billboard.d \
./src/osg/src/osgPlugins/ive/BlendColor.d \
./src/osg/src/osgPlugins/ive/BlendEquation.d \
./src/osg/src/osgPlugins/ive/BlendFunc.d \
./src/osg/src/osgPlugins/ive/BlinkSequence.d \
./src/osg/src/osgPlugins/ive/BumpMapping.d \
./src/osg/src/osgPlugins/ive/Camera.d \
./src/osg/src/osgPlugins/ive/CameraView.d \
./src/osg/src/osgPlugins/ive/Cartoon.d \
./src/osg/src/osgPlugins/ive/ClipNode.d \
./src/osg/src/osgPlugins/ive/ClipPlane.d \
./src/osg/src/osgPlugins/ive/ClusterCullingCallback.d \
./src/osg/src/osgPlugins/ive/ColorMask.d \
./src/osg/src/osgPlugins/ive/CompositeLayer.d \
./src/osg/src/osgPlugins/ive/ConeSector.d \
./src/osg/src/osgPlugins/ive/ConvexPlanarOccluder.d \
./src/osg/src/osgPlugins/ive/ConvexPlanarPolygon.d \
./src/osg/src/osgPlugins/ive/CoordinateSystemNode.d \
./src/osg/src/osgPlugins/ive/CullFace.d \
./src/osg/src/osgPlugins/ive/DOFTransform.d \
./src/osg/src/osgPlugins/ive/DataInputStream.d \
./src/osg/src/osgPlugins/ive/DataOutputStream.d \
./src/osg/src/osgPlugins/ive/Depth.d \
./src/osg/src/osgPlugins/ive/DirectionalSector.d \
./src/osg/src/osgPlugins/ive/DrawArrayLengths.d \
./src/osg/src/osgPlugins/ive/DrawArrays.d \
./src/osg/src/osgPlugins/ive/DrawElementsUByte.d \
./src/osg/src/osgPlugins/ive/DrawElementsUInt.d \
./src/osg/src/osgPlugins/ive/DrawElementsUShort.d \
./src/osg/src/osgPlugins/ive/Drawable.d \
./src/osg/src/osgPlugins/ive/Effect.d \
./src/osg/src/osgPlugins/ive/ElevationSector.d \
./src/osg/src/osgPlugins/ive/EllipsoidModel.d \
./src/osg/src/osgPlugins/ive/Exception.d \
./src/osg/src/osgPlugins/ive/FadeText.d \
./src/osg/src/osgPlugins/ive/Fog.d \
./src/osg/src/osgPlugins/ive/FragmentProgram.d \
./src/osg/src/osgPlugins/ive/FrontFace.d \
./src/osg/src/osgPlugins/ive/Geode.d \
./src/osg/src/osgPlugins/ive/Geometry.d \
./src/osg/src/osgPlugins/ive/Group.d \
./src/osg/src/osgPlugins/ive/HeightFieldLayer.d \
./src/osg/src/osgPlugins/ive/Image.d \
./src/osg/src/osgPlugins/ive/ImageLayer.d \
./src/osg/src/osgPlugins/ive/ImageSequence.d \
./src/osg/src/osgPlugins/ive/Impostor.d \
./src/osg/src/osgPlugins/ive/LOD.d \
./src/osg/src/osgPlugins/ive/Layer.d \
./src/osg/src/osgPlugins/ive/Light.d \
./src/osg/src/osgPlugins/ive/LightModel.d \
./src/osg/src/osgPlugins/ive/LightPoint.d \
./src/osg/src/osgPlugins/ive/LightPointNode.d \
./src/osg/src/osgPlugins/ive/LightSource.d \
./src/osg/src/osgPlugins/ive/LineStipple.d \
./src/osg/src/osgPlugins/ive/LineWidth.d \
./src/osg/src/osgPlugins/ive/Locator.d \
./src/osg/src/osgPlugins/ive/Material.d \
./src/osg/src/osgPlugins/ive/MatrixTransform.d \
./src/osg/src/osgPlugins/ive/MultiSwitch.d \
./src/osg/src/osgPlugins/ive/MultiTextureControl.d \
./src/osg/src/osgPlugins/ive/Multisample.d \
./src/osg/src/osgPlugins/ive/Node.d \
./src/osg/src/osgPlugins/ive/Object.d \
./src/osg/src/osgPlugins/ive/OccluderNode.d \
./src/osg/src/osgPlugins/ive/OcclusionQueryNode.d \
./src/osg/src/osgPlugins/ive/PagedLOD.d \
./src/osg/src/osgPlugins/ive/Point.d \
./src/osg/src/osgPlugins/ive/PointSprite.d \
./src/osg/src/osgPlugins/ive/PolygonMode.d \
./src/osg/src/osgPlugins/ive/PolygonOffset.d \
./src/osg/src/osgPlugins/ive/PolygonStipple.d \
./src/osg/src/osgPlugins/ive/PositionAttitudeTransform.d \
./src/osg/src/osgPlugins/ive/PrimitiveSet.d \
./src/osg/src/osgPlugins/ive/Program.d \
./src/osg/src/osgPlugins/ive/ProxyNode.d \
./src/osg/src/osgPlugins/ive/ReaderWriterIVE.d \
./src/osg/src/osgPlugins/ive/Scissor.d \
./src/osg/src/osgPlugins/ive/Scribe.d \
./src/osg/src/osgPlugins/ive/Sequence.d \
./src/osg/src/osgPlugins/ive/ShadeModel.d \
./src/osg/src/osgPlugins/ive/Shader.d \
./src/osg/src/osgPlugins/ive/Shape.d \
./src/osg/src/osgPlugins/ive/ShapeAttributeList.d \
./src/osg/src/osgPlugins/ive/ShapeDrawable.d \
./src/osg/src/osgPlugins/ive/SpecularHighlights.d \
./src/osg/src/osgPlugins/ive/StateSet.d \
./src/osg/src/osgPlugins/ive/Stencil.d \
./src/osg/src/osgPlugins/ive/StencilTwoSided.d \
./src/osg/src/osgPlugins/ive/Switch.d \
./src/osg/src/osgPlugins/ive/SwitchLayer.d \
./src/osg/src/osgPlugins/ive/Terrain.d \
./src/osg/src/osgPlugins/ive/TerrainTile.d \
./src/osg/src/osgPlugins/ive/TexEnv.d \
./src/osg/src/osgPlugins/ive/TexEnvCombine.d \
./src/osg/src/osgPlugins/ive/TexGen.d \
./src/osg/src/osgPlugins/ive/TexGenNode.d \
./src/osg/src/osgPlugins/ive/TexMat.d \
./src/osg/src/osgPlugins/ive/Text.d \
./src/osg/src/osgPlugins/ive/Text3D.d \
./src/osg/src/osgPlugins/ive/Texture.d \
./src/osg/src/osgPlugins/ive/Texture1D.d \
./src/osg/src/osgPlugins/ive/Texture2D.d \
./src/osg/src/osgPlugins/ive/Texture2DArray.d \
./src/osg/src/osgPlugins/ive/Texture3D.d \
./src/osg/src/osgPlugins/ive/TextureCubeMap.d \
./src/osg/src/osgPlugins/ive/TextureRectangle.d \
./src/osg/src/osgPlugins/ive/Transform.d \
./src/osg/src/osgPlugins/ive/Uniform.d \
./src/osg/src/osgPlugins/ive/VertexProgram.d \
./src/osg/src/osgPlugins/ive/Viewport.d \
./src/osg/src/osgPlugins/ive/VisibilityGroup.d \
./src/osg/src/osgPlugins/ive/Volume.d \
./src/osg/src/osgPlugins/ive/VolumeCompositeLayer.d \
./src/osg/src/osgPlugins/ive/VolumeCompositeProperty.d \
./src/osg/src/osgPlugins/ive/VolumeImageLayer.d \
./src/osg/src/osgPlugins/ive/VolumeLayer.d \
./src/osg/src/osgPlugins/ive/VolumeLocator.d \
./src/osg/src/osgPlugins/ive/VolumePropertyAdjustmentCallback.d \
./src/osg/src/osgPlugins/ive/VolumeScalarProperty.d \
./src/osg/src/osgPlugins/ive/VolumeSwitchProperty.d \
./src/osg/src/osgPlugins/ive/VolumeTile.d \
./src/osg/src/osgPlugins/ive/VolumeTransferFunctionProperty.d 


# Each subdirectory must supply rules for building sources it contributes
src/osg/src/osgPlugins/ive/%.o: ../src/osg/src/osgPlugins/ive/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: Cross G++ Compiler'
	g++ -std=c++11 -I/usr/include/gtk-3.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/pixman-1 -I/usr/include/libpng12 -O0 -g3 -Wall -c -fmessage-length=0 `pkg-config --cflags gtk+-3.0` -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


